# Load data

In [1]:
import json
import pandas as pd

In [2]:
! ls daten_goldstandard/

master.json slave.json  unique.json

In [3]:
records_master = []
records_slave = []
records_unique = []
for line in open('./daten_goldstandard/master.json', 'r'):
    records_master.append(json.loads(line))
for line in open('./daten_goldstandard/slave.json', 'r'):
    records_slave.append(json.loads(line))
for line in open('./daten_goldstandard/unique.json', 'r'):
    records_unique.append(json.loads(line))

len(records_master), len(records_slave), len(records_unique)

(159, 435, 596)

In [4]:
df_m = pd.DataFrame(records_master)
df_s = pd.DataFrame(records_slave)
df_u = pd.DataFrame(records_unique)

len(df_m.columns), len(df_s.columns), len(df_u.columns)

(23, 23, 23)

In [5]:
# Extend display to number of columns of DataFrame
pd.options.display.max_columns = len(df_m.columns)

df_m.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"[(IDSBB)002447452, (ALEX)9912923344101791]",2000,[],[],2000,264853032,[],,2000,"[BK020000, BK020800]",[0-87834-101-3],[],,[319 S.],"[Vol. 26, 26, 2000]","[[ChuC.Y. Cyrus, LeeRonald Demos(DE-588)157411...",[],[],2000,,[Population and economic change in East Asia],[Population and economic change in East Asia],[319 S.]
1,"[(IDSBB)000369647, (NEBIS)005609528]",1978,[],[],1978,264853288,[],,1978,[BK020000],[],[],,[252 S.],[33001/680],[[SchikanederEmanuel1751-1812(DE-588)11860757X...,[],[],1978,,[Die Zauberflöte],[Die Zauberflöte],[252 S.]
2,"[(IDSLU)001293605, (IDSBB)006725532, (NEBIS)01...",2017,[],[],2017,264853539,[],,2017,[BK010000],[],[],,[74 Seiten],[Nr. 313 (August 2017)],[[SchneiderReto U.1963-(DE-588)115417206Verfas...,[],[],2017,,"[Alles Wissen dieser Welt, warum Bibliotheken ...","[Alles Wissen dieser Welt, warum Bibliotheken ...",[74 Seiten]
3,"[(NATIONALLICENCE)oxford-10.1093/cid/ciu795, (...",2015,[],[],2015,264853784,[10.1093/cid/ciu795],,20150201,[BK010053],[],[10.1093/cid/ciu795],,[],"[60/3(2015-02-01), 432-437]",[[RozotVirginieDivision of Immunology and Alle...,[],[],20150201,,[Combined Use of Mycobacterium tuberculosis-Sp...,[Combined Use of Mycobacterium tuberculosis-Sp...,[]
4,"[(NATIONALLICENCE)oxford-10.1093/ndt/gft319, (...",2013,[],[],2013,264854039,[10.1093/ndt/gft319],,201310,[BK010053],[],[10.1093/ndt/gft319],,[],"[28/10(2013-10), 2421-2431]",[[BonnyOlivierDepartment of Pharmacology and T...,[],[],201310,,[Molecular bases of circadian rhythmicity in r...,[Molecular bases of circadian rhythmicity in r...,[]

In [6]:
df_s.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"[(OCoLC)731635279, (ABN)000539983]",2009,[],[],2009,000311049,[],,2009,[BK020000],[978-3-15-020008-7],[],,[600 S.],[20008],"[[GraweChristian, GraweUrsula], [Jane Austen ;...",[Reclam jun.],[Reclam jun.],2009,,"[Emma, Roman]","[Emma, Roman]",[600 S.]
1,"[(OCoLC)808324878, (ABN)000155059]",2000,[],"[Metropolitan Opera Orchestra, Metropolitan Op...",2000,00130724X,[],,2000,[VM010300],[],[],,"[1 DVD-Video, DVD Region 0, 169 Min., farb.]",[],"[[MozartWolfgang Amadeus, LevineJames, Schikan...",[Deutsche Grammophon],[Deutsche Grammophon],2000,,"[Die Zauberflöte, Oper in zwei Aufzügen]","[Die Zauberflöte, Oper in zwei Aufzügen]","[1 DVD-Video, DVD Region 0, 169 Min., farb.]"
2,"[(OCoLC)231772550, (ABN)000096920]",1999,[],[],1999,001817272,[],,1999,[BK020000],[3-495-47879-5],[],,[316 S.],[],[[Andreas Flury]],[Alber],[Alber],1999,,"[Der moralische Status der Tiere, Henry Salt, ...","[Der moralische Status der Tiere, Henry Salt, ...",[316 S.]
3,"[(OCoLC)887157168, (ABN)000223912]",uuuu,[],[],uuuu,00236865X,[],,uuuuuuuu,[BK020000],[],[],,[412 S.],[],[[]],[Ernst Eulenburg],[Ernst Eulenburg],uuuuuuuu,,[Die Zauberflöte],[Die Zauberflöte],[412 S.]
4,"[(OCoLC)887324690, (ABN)000548154]",2008,[],[],2008,00351031X,[],,2008,[BK020000],[978-1-4058-8214-9],[],,[64 S.],[],"[[StrangeJoanna], [Jane Austen ; retold by Joa...",[Pearson Education],[Pearson Education],2008,,[Emma],[Emma],[64 S.]

In [7]:
df_u.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"[(OCoLC)362722306, (ABN)000551177]",2009,[],[],2009,000143235,[],,2009,[BK020000],[978-3-7466-6120-9],[],,[575 S.],[6120],[[Jane Austen]],[Aufbau Taschenbuch],[Aufbau Taschenbuch],2009,,"[Emma, Roman]","[Emma, Roman]",[575 S.]
1,"[(OCoLC)886929897, (ABN)000223034]",2004,[],[Wiener Philharmoniker],2004,00044801X,[],,2004,[MU040100],[],[],,[2 CD],[],"[[KarajanHerbert von], []]",[Membran],[Membran],2004,,[Die Zauberflöte],[Die Zauberflöte],[2 CD]
2,"[(OCoLC)778386601, (ABN)000433604]",1793,[],[],1793,000996009,[],,17931797,[MU010000],[],[],,[202 S.],[],[[Wolfgang Amadeus Mozart]],[Komm. Breitkopf],[Komm. Breitkopf],17931797,,"[Die Zauberflöte, eine grosse Oper in zwey Auf...","[Die Zauberflöte, eine grosse Oper in zwey Auf...",[202 S.]
3,"[(OCoLC)778561839, (ABN)000238844]",2000,[],[],2000,00239538X,[],,2000,[BK020047],[3-932992-42-3],[],,"[1 CD-Rom in Box, mit Notizbuchfunktion für Re...",[],"[[FrischMax1911-1991(DE-588)118536109], [Max F...",[Terzio],[Terzio],2000,,"[Homo faber, Originaltext, Interpretation, Bio...","[Homo faber, Originaltext, Interpretation, Bio...","[1 CD-Rom in Box, mit Notizbuchfunktion für Re..."
4,"[(OCoLC)777853583, (ABN)000243260]",1990,[],[],1990,002410559,[],,1990,[BK020000],[0-19-282756-1],[],,[445 p.],[],[[Jane Austen]],[Oxford University Press],[Oxford University Press],1990,,[Emma],[Emma],[445 p.]

## Transform list columns to string columns

In [8]:
def transform_list_to_string(df, column):
    df[column] = [', '.join(map(str, list_element)) for list_element in df[column]]
    
    return df

In [9]:
list_columns = ['coordinate', 'corporate', 'pages', 'part', 'pubword',
                'ttlfull', 'ttlpart']
array_of_strings_columns = ['person']

for list_col in list_columns:
    df_m = transform_list_to_string(df_m, list_col)
    df_s = transform_list_to_string(df_s, list_col)
    df_u = transform_list_to_string(df_u, list_col)

for aos_col in array_of_strings_columns:
    df_m = transform_list_to_string(df_m, aos_col)
    df_s = transform_list_to_string(df_s, aos_col)
    df_u = transform_list_to_string(df_u, aos_col)
    
# Additional
df_s = transform_list_to_string(df_s, '035liste')
df_u = transform_list_to_string(df_u, '035liste')

In [10]:
df_m.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"[(IDSBB)002447452, (ALEX)9912923344101791]",2000,,,2000,264853032,[],,2000,"[BK020000, BK020800]",[0-87834-101-3],[],,319 S.,"Vol. 26, 26, 2000","['ChuC.Y. Cyrus', 'LeeRonald Demos(DE-588)1574...",[],,2000,,Population and economic change in East Asia,Population and economic change in East Asia,[319 S.]
1,"[(IDSBB)000369647, (NEBIS)005609528]",1978,,,1978,264853288,[],,1978,[BK020000],[],[],,252 S.,33001/680,['SchikanederEmanuel1751-1812(DE-588)11860757X...,[],,1978,,Die Zauberflöte,Die Zauberflöte,[252 S.]
2,"[(IDSLU)001293605, (IDSBB)006725532, (NEBIS)01...",2017,,,2017,264853539,[],,2017,[BK010000],[],[],,74 Seiten,Nr. 313 (August 2017),['SchneiderReto U.1963-(DE-588)115417206Verfas...,[],,2017,,"Alles Wissen dieser Welt, warum Bibliotheken n...","Alles Wissen dieser Welt, warum Bibliotheken n...",[74 Seiten]
3,"[(NATIONALLICENCE)oxford-10.1093/cid/ciu795, (...",2015,,,2015,264853784,[10.1093/cid/ciu795],,20150201,[BK010053],[],[10.1093/cid/ciu795],,,"60/3(2015-02-01), 432-437",['RozotVirginieDivision of Immunology and Alle...,[],,20150201,,Combined Use of Mycobacterium tuberculosis-Spe...,Combined Use of Mycobacterium tuberculosis-Spe...,[]
4,"[(NATIONALLICENCE)oxford-10.1093/ndt/gft319, (...",2013,,,2013,264854039,[10.1093/ndt/gft319],,201310,[BK010053],[],[10.1093/ndt/gft319],,,"28/10(2013-10), 2421-2431",['BonnyOlivierDepartment of Pharmacology and T...,[],,201310,,Molecular bases of circadian rhythmicity in re...,Molecular bases of circadian rhythmicity in re...,[]

In [11]:
comp_str = 'Biblio'

df_m[df_m.ttlfull.str.contains(comp_str)]

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
2,"[(IDSLU)001293605, (IDSBB)006725532, (NEBIS)01...",2017,,,2017,264853539,[],,2017,[BK010000],[],[],,74 Seiten,Nr. 313 (August 2017),['SchneiderReto U.1963-(DE-588)115417206Verfas...,[],,2017,,"Alles Wissen dieser Welt, warum Bibliotheken n...","Alles Wissen dieser Welt, warum Bibliotheken n...",[74 Seiten]
148,"[(SBT)000781193, (RERO)R008489733]",2015,,,2015,504390775,[],,20151475,[BK020000],[978-88-7922-121-4],[],,2 vol.,"n. 1, 1","['LapiniBernardo'], ['Francesco Petrarca ; com...","[ADV, Biblioteca cantonale di Lugano]","ADV, Biblioteca cantonale di Lugano",20151475,,"Trionfi, riedizione accurata dell'incunabolo c...","Trionfi, riedizione accurata dell'incunabolo c...",[2 vol.]

In [12]:
# Python RegEx library for string compare
import re

def master_slaves_compare(masters, slaves, i, j):
    search_string = re.sub(r'\(', '\(', masters['035liste'].loc[i][j])
    search_string = re.sub(r'\)', '\)', search_string)
    print('\nmaster index {:d}, slave relation {:d}, {:s}'.format(i, j, search_string))
    
    slave_index = slaves[slaves['035liste'].str.contains(search_string)].index
    
    return slave_index

In [13]:
for i in range(len(df_m)):
    for j in range(len(df_m['035liste'].loc[i])):
        slave_index = master_slaves_compare(df_m, df_u, i, j)

        df_united = pd.concat([df_m.loc[[i]], df_u.iloc[slave_index]], axis=0)
        print(df_united.drop(columns=['035liste', 'docid']).duplicated())

master index 0, slave relation 0, \(IDSBB\)002447452

TypeError: unhashable type: 'list'

In [ ]:
# Look at sample cases
df_m.loc[0], df_u.loc[107]

In [ ]:
# Look at sample cases, manually
master_index = 2

slave_index = master_slaves_compare(df_m, df_u, master_index, 0)

df_united = pd.concat([df_m.loc[[master_index]], df_u.iloc[slave_index]], axis=0)
df_united

## Find duplicates

In [ ]:
def find_duplicates(df):
    df_duplicates = df[df.drop(columns=['035liste', 'docid']).duplicated(keep=False)].sort_values(by='ttlfull')
    
    return df_duplicates

In [ ]:
find_duplicates(df_u)

In [ ]:
df_m.loc[90]

In [ ]:
df_u.loc[367], df_u.loc[61]

In [ ]:
print(df_m.decade.unique())

df_m_d_sd = df_m.decade.sort_values()
for i in range(len(df_m_d_sd)):
    print(df_m_d_sd[i])

In [ ]:
print(df_m.exactDate.unique())

df_m_d_sd = df_m.exactDate.sort_values()
for i in range(len(df_m_d_sd)):
    print(df_m_d_sd[i])