# Load data

In [1]:
import json
import pandas as pd

In [2]:
! ls daten_goldstandard/

master.json slave.json  unique.json

In [3]:
records_master = []
records_slave = []
records_unique = []
for line in open('./daten_goldstandard/master.json', 'r'):
    records_master.append(json.loads(line))
for line in open('./daten_goldstandard/slave.json', 'r'):
    records_slave.append(json.loads(line))
for line in open('./daten_goldstandard/unique.json', 'r'):
    records_unique.append(json.loads(line))

len(records_master), len(records_slave), len(records_unique)

(159, 435, 596)

In [4]:
df_m = pd.DataFrame(records_master)
df_s = pd.DataFrame(records_slave)
df_u = pd.DataFrame(records_unique)

len(df_m.columns), len(df_s.columns), len(df_u.columns)

(23, 23, 23)

In [5]:
# Extend display to number of columns of DataFrame
pd.options.display.max_columns = len(df_m.columns)

df_m.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"[(IDSBB)002447452, (ALEX)9912923344101791]",2000,[],{},2000,264853032,[],,2000,"[BK020000, BK020800]",[0-87834-101-3],[],,[319 S.],"[Vol. 26, 26, 2000]","{'100': [], '700': ['ChuC.Y. Cyrus', 'LeeRonal...",[],[],2000,,{'245': ['Population and economic change in Ea...,{'245': ['Population and economic change in Ea...,[319 S.]
1,"[(IDSBB)000369647, (NEBIS)005609528]",1978,[],{},1978,264853288,[],,1978,[BK020000],[],[],,[252 S.],[33001/680],{'100': ['MozartWolfgang Amadeus1756-1791(DE-5...,[],[],1978,,{'245': ['Die Zauberflöte']},{'245': ['Die Zauberflöte']},[252 S.]
2,"[(IDSLU)001293605, (IDSBB)006725532, (NEBIS)01...",2017,[],{},2017,264853539,[],,2017,[BK010000],[],[],,[74 Seiten],[Nr. 313 (August 2017)],"{'100': [], '700': ['SchneiderReto U.1963-(DE-...",[],[],2017,,"{'245': ['Alles Wissen dieser Welt', 'warum Bi...","{'245': ['Alles Wissen dieser Welt', 'warum Bi...",[74 Seiten]
3,"[(NATIONALLICENCE)oxford-10.1093/cid/ciu795, (...",2015,[],{},2015,264853784,[10.1093/cid/ciu795],,20150201,[BK010053],[],[10.1093/cid/ciu795],,[],"[60/3(2015-02-01), 432-437]","{'100': [], '700': ['RozotVirginieDivision of ...",[],[],20150201,,{'245': ['Combined Use of Mycobacterium tuberc...,{'245': ['Combined Use of Mycobacterium tuberc...,[]
4,"[(NATIONALLICENCE)oxford-10.1093/ndt/gft319, (...",2013,[],{},2013,264854039,[10.1093/ndt/gft319],,201310,[BK010053],[],[10.1093/ndt/gft319],,[],"[28/10(2013-10), 2421-2431]","{'100': [], '700': ['BonnyOlivierDepartment of...",[],[],201310,,{'245': ['Molecular bases of circadian rhythmi...,{'245': ['Molecular bases of circadian rhythmi...,[]

In [6]:
df_s.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"[(OCoLC)731635279, (ABN)000539983]",2009,[],{},2009,000311049,[],,2009,[BK020000],[978-3-15-020008-7],[],,[600 S.],[20008],{'100': ['AustenJane1775-1817(DE-588)118505173...,[Reclam jun.],[Reclam jun.],2009,,"{'245': ['Emma', 'Roman']}","{'245': ['Emma', 'Roman']}",[600 S.]
1,"[(OCoLC)808324878, (ABN)000155059]",2000,[],"{'710': ['Metropolitan Opera Orchestra', 'Metr...",2000,00130724X,[],,2000,[VM010300],[],[],,"[1 DVD-Video, DVD Region 0, 169 Min., farb.]",[],"{'100': ['LevineJamesDir.'], '700': ['MozartWo...",[Deutsche Grammophon],[Deutsche Grammophon],2000,,"{'245': ['Die Zauberflöte', 'Oper in zwei Aufz...","{'245': ['Die Zauberflöte', 'Oper in zwei Aufz...","[1 DVD-Video, DVD Region 0, 169 Min., farb.]"
2,"[(OCoLC)231772550, (ABN)000096920]",1999,[],{},1999,001817272,[],,1999,[BK020000],[3-495-47879-5],[],,[316 S.],[],"{'100': ['FluryAndreas'], '245c': ['Andreas Fl...",[Alber],[Alber],1999,,"{'245': ['Der moralische Status der Tiere', 'H...","{'245': ['Der moralische Status der Tiere', 'H...",[316 S.]
3,"[(OCoLC)887157168, (ABN)000223912]",uuuu,[],{},uuuu,00236865X,[],,uuuuuuuu,[BK020000],[],[],,[412 S.],[],"{'100': ['MozartWolfgang Amadeus'], '245c': ['']}",[Ernst Eulenburg],[Ernst Eulenburg],uuuuuuuu,,{'245': ['Die Zauberflöte']},{'245': ['Die Zauberflöte']},[412 S.]
4,"[(OCoLC)887324690, (ABN)000548154]",2008,[],{},2008,00351031X,[],,2008,[BK020000],[978-1-4058-8214-9],[],,[64 S.],[],{'100': ['AustenJane1775-1817(DE-588)118505173...,[Pearson Education],[Pearson Education],2008,,{'245': ['Emma']},{'245': ['Emma']},[64 S.]

In [7]:
df_u.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"[(OCoLC)362722306, (ABN)000551177]",2009,[],{},2009,000143235,[],,2009,[BK020000],[978-3-7466-6120-9],[],,[575 S.],[6120],{'100': ['AustenJane1775-1817(DE-588)118505173...,[Aufbau Taschenbuch],[Aufbau Taschenbuch],2009,,"{'245': ['Emma', 'Roman']}","{'245': ['Emma', 'Roman']}",[575 S.]
1,"[(OCoLC)886929897, (ABN)000223034]",2004,[],{'710': ['Wiener Philharmoniker']},2004,00044801X,[],,2004,[MU040100],[],[],,[2 CD],[],{'100': ['MozartWolfgang Amadeus1756-1791(DE-5...,[Membran],[Membran],2004,,{'245': ['Die Zauberflöte']},{'245': ['Die Zauberflöte']},[2 CD]
2,"[(OCoLC)778386601, (ABN)000433604]",1793,[],{},1793,000996009,[],,17931797,[MU010000],[],[],,[202 S.],[],"{'100': ['MozartWolfgang Amadeus'], '245c': ['...",[Komm. Breitkopf],[Komm. Breitkopf],17931797,,"{'245': ['Die Zauberflöte', 'eine grosse Oper ...","{'245': ['Die Zauberflöte', 'eine grosse Oper ...",[202 S.]
3,"[(OCoLC)778561839, (ABN)000238844]",2000,[],{},2000,00239538X,[],,2000,[BK020047],[3-932992-42-3],[],,"[1 CD-Rom in Box, mit Notizbuchfunktion für Re...",[],"{'100': [], '700': ['FrischMax1911-1991(DE-588...",[Terzio],[Terzio],2000,,"{'245': ['Homo faber', 'Originaltext, Interpre...","{'245': ['Homo faber', 'Originaltext, Interpre...","[1 CD-Rom in Box, mit Notizbuchfunktion für Re..."
4,"[(OCoLC)777853583, (ABN)000243260]",1990,[],{},1990,002410559,[],,1990,[BK020000],[0-19-282756-1],[],,[445 p.],[],{'100': ['AustenJane1775-1817(DE-588)118505173...,[Oxford University Press],[Oxford University Press],1990,,{'245': ['Emma']},{'245': ['Emma']},[445 p.]

## Transform list columns to string columns

In [8]:
def transform_list_to_string(df, column):
    df[column] = [', '.join(map(str, list_element)) for list_element in df[column]]
    
    return df

In [9]:
list_columns = ['coordinate', 'corporate', 'pages', 'part', 'pubword',
                'ttlfull', 'ttlpart',
                'doi', 'format', 'isbn', 'ismn', 'pubinit', 'volumes']
array_of_strings_columns = ['person']
#strings_columns = ['century', 'edition', 'exactDate', 'musicid', 'pubyear', 'scale']

for list_col in list_columns:
    df_m = transform_list_to_string(df_m, list_col)
    df_s = transform_list_to_string(df_s, list_col)
    df_u = transform_list_to_string(df_u, list_col)

for aos_col in array_of_strings_columns:
    df_m = transform_list_to_string(df_m, aos_col)
    df_s = transform_list_to_string(df_s, aos_col)
    df_u = transform_list_to_string(df_u, aos_col)
    
# Additional
df_s = transform_list_to_string(df_s, '035liste')
df_u = transform_list_to_string(df_u, '035liste')

In [10]:
df_m.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"[(IDSBB)002447452, (ALEX)9912923344101791]",2000,,,2000,264853032,,,2000,"BK020000, BK020800",0-87834-101-3,,,319 S.,"Vol. 26, 26, 2000","100, 700, 245c",,,2000,,245,245,319 S.
1,"[(IDSBB)000369647, (NEBIS)005609528]",1978,,,1978,264853288,,,1978,BK020000,,,,252 S.,33001/680,"100, 700, 245c",,,1978,,245,245,252 S.
2,"[(IDSLU)001293605, (IDSBB)006725532, (NEBIS)01...",2017,,,2017,264853539,,,2017,BK010000,,,,74 Seiten,Nr. 313 (August 2017),"100, 700, 245c",,,2017,,"245, 246",245,74 Seiten
3,"[(NATIONALLICENCE)oxford-10.1093/cid/ciu795, (...",2015,,,2015,264853784,10.1093/cid/ciu795,,20150201,BK010053,,10.1093/cid/ciu795,,,"60/3(2015-02-01), 432-437","100, 700, 245c",,,20150201,,245,245,
4,"[(NATIONALLICENCE)oxford-10.1093/ndt/gft319, (...",2013,,,2013,264854039,10.1093/ndt/gft319,,201310,BK010053,,10.1093/ndt/gft319,,,"28/10(2013-10), 2421-2431","100, 700, 245c",,,201310,,245,245,

In [11]:
df_u.head()

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
0,"(OCoLC)362722306, (ABN)000551177",2009,,,2009,000143235,,,2009,BK020000,978-3-7466-6120-9,,,575 S.,6120,"100, 245c",Aufbau Taschenbuch,Aufbau Taschenbuch,2009,,245,245,575 S.
1,"(OCoLC)886929897, (ABN)000223034",2004,,710,2004,00044801X,,,2004,MU040100,,,,2 CD,,"100, 700, 245c",Membran,Membran,2004,,245,245,2 CD
2,"(OCoLC)778386601, (ABN)000433604",1793,,,1793,000996009,,,17931797,MU010000,,,,202 S.,,"100, 245c",Komm. Breitkopf,Komm. Breitkopf,17931797,,245,245,202 S.
3,"(OCoLC)778561839, (ABN)000238844",2000,,,2000,00239538X,,,2000,BK020047,3-932992-42-3,,,"1 CD-Rom in Box, mit Notizbuchfunktion für Ref...",,"100, 700, 245c",Terzio,Terzio,2000,,245,245,"1 CD-Rom in Box, mit Notizbuchfunktion für Ref..."
4,"(OCoLC)777853583, (ABN)000243260",1990,,,1990,002410559,,,1990,BK020000,0-19-282756-1,,,445 p.,,"100, 245c",Oxford University Press,Oxford University Press,1990,,245,245,445 p.

In [12]:
comp_str = 'Biblio'

df_m[df_m.ttlfull.str.contains(comp_str)]

Empty DataFrame
Columns: [035liste, century, coordinate, corporate, decade, docid, doi, edition, exactDate, format, isbn, ismn, musicid, pages, part, person, pubinit, pubword, pubyear, scale, ttlfull, ttlpart, volumes]
Index: []

In [13]:
# Python RegEx library for string compare
import re

def master_slaves_compare(masters, slaves, i, j):
    search_string = re.sub(r'\(', '\(', masters['035liste'].loc[i][j])
    search_string = re.sub(r'\)', '\)', search_string)
    print('\nmaster index {:d}, slave relation {:d}, {:s}'.format(i, j, search_string))
    
    slave_index = slaves[slaves['035liste'].str.contains(search_string)].index
    
    return slave_index

In [23]:
df_s['035liste']

0                       (OCoLC)731635279, (ABN)000539983
1                       (OCoLC)808324878, (ABN)000155059
2                       (OCoLC)231772550, (ABN)000096920
3                       (OCoLC)887157168, (ABN)000223912
4                       (OCoLC)887324690, (ABN)000548154
5                       (OCoLC)180154028, (ABN)000308006
6                       (OCoLC)605622457, (ABN)000234417
7                       (OCoLC)887393628, (ABN)000218626
8                       (OCoLC)778329562, (ABN)000048149
9                       (OCoLC)780137741, (ABN)000669941
10                      (OCoLC)634380788, (ABN)000295774
11                      (OCoLC)887478782, (ABN)000327579
12                      (OCoLC)808324878, (ABN)000250841
13                      (OCoLC)254941323, (BGR)000336877
14                      (OCoLC)887618219, (BGR)000347882
15                      (OCoLC)887620487, (BGR)000384903
16                      (OCoLC)808016835, (BGR)000107522
17                      (OCoLC)636062037, (BGR)000409509
18                      (OCoLC)610693897, (BGR)000009742
19                      (OCoLC)218626148, (BGR)000463276
20                      (OCoLC)808021169, (BGR)000119170
21                      (OCoLC)887478782, (BGR)000384263
22                       (OCoLC)82420125, (BGR)000141165
23                    (OCoLC)611221513, (IDSLU)000438850
24                    (OCoLC)885258089, (IDSLU)000296294
25                    (OCoLC)695884327, (IDSLU)000901978
26                    (OCoLC)611969127, (IDSLU)000489765
27                    (OCoLC)885293308, (IDSLU)000900593
28                    (OCoLC)885295528, (IDSLU)000411402
29                    (OCoLC)218626148, (IDSLU)000449481
                             ...
405                   (OCoLC)695771775, (NEBIS)010817639
406                                        (RERO)1083290
407                    (SNL)vtls001887640, (Sz)001887640
408                    (SNL)vtls001887658, (Sz)001887658
409                    (SNL)vtls001887659, (Sz)001887659
410                    (SNL)vtls001887704, (Sz)001887704
411                    (SNL)vtls001889387, (Sz)001889387
412                   (OCoLC)806965128, (IDSLU)001278755
413                   (OCoLC)985604872, (NEBIS)010889835
414         (SERSOL)ssj0000328745, (WaSeSS)ssj0000328745
415                   (OCoLC)991619642, (IDSBB)006708762
416                                            (HEMU)357
417                                            (HEMU)358
418                                           (HEMU)1153
419                                           (HEMU)9473
420                                          (HEMU)27700
421                                          (HEMU)35952
422                    (OCoLC)999841337, (SGBN)001396584
423                  (OCoLC)1001245300, (NEBIS)010967948
424                  (OCoLC)1002177443, (IDSBB)006726594
425                  (OCoLC)1002912504, (IDSBB)006725532
426                                     (NEBIS)011007027
427                  (OCoLC)1002912504, (IDSLU)001293605
428    (OCoLC)1002177443, (NEBIS)011045420, (OCoLC)10...
429    (VAUD)991010321879702852, (RNV)000202321-41bcu...
430                    (OCoLC)891914550, (SGBN)001351177
431                     (OCoLC)884694486, (ABN)000817339
432                                         (KBTG)128844
433                                         (KBTG)131754
434                                         (KBTG)263228
Name: 035liste, Length: 435, dtype: object

In [14]:
for i in range(len(df_m)):
    for j in range(len(df_m['035liste'].loc[i])):
        slave_index = master_slaves_compare(df_m, df_s, i, j)

        df_united = pd.concat([df_m.loc[[i]], df_s.iloc[slave_index]], axis=0)
        print(df_united.drop(columns=['035liste', 'docid']).duplicated())
#        print(df_united.drop(columns=['035liste', 'docid']))

master index 0, slave relation 0, \(IDSBB\)002447452
0      False
107    False
dtype: bool

master index 0, slave relation 1, \(ALEX\)9912923344101791
0      False
307    False
dtype: bool

master index 1, slave relation 0, \(IDSBB\)000369647
1      False
133     True
dtype: bool

master index 1, slave relation 1, \(NEBIS\)005609528
1      False
167    False
dtype: bool

master index 2, slave relation 0, \(IDSLU\)001293605
2      False
427    False
dtype: bool

master index 2, slave relation 1, \(IDSBB\)006725532
2      False
425    False
dtype: bool

master index 2, slave relation 2, \(NEBIS\)010967948
2      False
423    False
dtype: bool

master index 2, slave relation 3, \(SGBN\)001396584
2      False
422    False
dtype: bool

master index 3, slave relation 0, \(NATIONALLICENCE\)oxford-10.1093/cid/ciu795
3      False
347     True
dtype: bool

master index 3, slave relation 1, \(SERVAL\)BIB_35203E0F848B
3      False
280    False
dtype: bool

master index 4, slave relation 0, \(NATIONALLICENCE\)oxford-10.1093/ndt/gft319
4      False
349     True
dtype: bool

master index 4, slave relation 1, \(SERVAL\)BIB_D4E58F4B31B0
4      False
278    False
dtype: bool

master index 5, slave relation 0, \(IDSBB\)006349742
5      False
284    False
dtype: bool

master index 5, slave relation 1, \(SNL\)vtls001511583
5     False
91    False
dtype: bool

master index 5, slave relation 2, \(OCoLC\)428090797
5      False
284    False
dtype: bool

master index 5, slave relation 3, \(Sz\)001511583
5     False
91    False
dtype: bool

master index 6, slave relation 0, \(NEBIS\)009544280
6      False
186     True
dtype: bool

master index 6, slave relation 1, \(SNL\)vtls000622833
6     False
82    False
dtype: bool

master index 6, slave relation 2, \(Sz\)000622833
6     False
82    False
dtype: bool

master index 7, slave relation 0, \(NEBIS\)002605093
7      False
152    False
dtype: bool

master index 7, slave relation 1, \(SBT\)000026281
7     False
56    False
dtype: bool

master index 7, slave relation 2, \(RERO\)0763942
7      False
195    False
dtype: bool

master index 7, slave relation 3, \(VAUD\)991008744179702852
7      False
384    False
dtype: bool

master index 7, slave relation 4, \(RNV\)000692553-41bculausa_network
7      False
384    False
dtype: bool

master index 7, slave relation 5, \(RERO\)000692553
7      False
384    False
dtype: bool

master index 7, slave relation 6, 0763942
7      False
195    False
384     True
dtype: bool

master index 7, slave relation 7, \(EXLNZ-41BCULAUSA_NETWORK\)991021679809702851
7      False
384    False
dtype: bool

master index 8, slave relation 0, \(SBT\)000762391
8      False
288    False
dtype: bool

master index 8, slave relation 1, \(VAUD\)991001881179702852
8      False
397    False
dtype: bool

master index 8, slave relation 2, \(RNV\)008065631-41bculausa_network
8      False
397    False
dtype: bool

master index 8, slave relation 3, \(RERO\)008065631
8      False
397    False
dtype: bool

master index 8, slave relation 4, R008065631
8      False
397    False
dtype: bool

master index 8, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991016285219702851
8      False
397    False
dtype: bool

master index 9, slave relation 0, \(RERO\)R008339403
9      False
313     True
dtype: bool

master index 9, slave relation 1, \(VAUD\)991004649259702852
9      False
372     True
dtype: bool

master index 9, slave relation 2, \(RNV\)008339403-41bculausa_network
9      False
372     True
dtype: bool

master index 9, slave relation 3, \(RERO\)008339403
9      False
372     True
dtype: bool

master index 9, slave relation 4, R008339403
9      False
313     True
372     True
dtype: bool

master index 9, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991019142859702851
9      False
372     True
dtype: bool

master index 10, slave relation 0, \(RERO\)1083290
10     False
406     True
dtype: bool

master index 10, slave relation 1, \(VAUD\)991008451129702852
10     False
401     True
dtype: bool

master index 10, slave relation 2, \(RNV\)003748654-41bculausa_network
10     False
401     True
dtype: bool

master index 10, slave relation 3, \(RERO\)003748654
10     False
401     True
dtype: bool

master index 10, slave relation 4, 1083290
10     False
401     True
406     True
dtype: bool

master index 10, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991006788929702851
10     False
401     True
dtype: bool

master index 11, slave relation 0, \(RERO\)R003786003
11     False
226     True
dtype: bool

master index 11, slave relation 1, \(VAUD\)991008917219702852
11     False
380     True
dtype: bool

master index 11, slave relation 2, \(RNV\)003786003-41bculausa_network
11     False
380     True
dtype: bool

master index 11, slave relation 3, \(RERO\)003786003
11     False
380     True
dtype: bool

master index 11, slave relation 4, R003786003
11     False
226     True
380     True
dtype: bool

master index 11, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991007195409702851
11     False
380     True
dtype: bool

master index 12, slave relation 0, \(IDSLU\)000568353
12    False
47    False
dtype: bool

master index 12, slave relation 1, \(RERO\)R006199229
12     False
246    False
dtype: bool

master index 13, slave relation 0, \(BGR\)000347882
13    False
14     True
dtype: bool

master index 13, slave relation 1, \(NEBIS\)005038859
13     False
162    False
dtype: bool

master index 13, slave relation 2, \(ABN\)000218626
13    False
7     False
dtype: bool

master index 14, slave relation 0, \(SGBN\)000443345
14    False
64    False
dtype: bool

master index 14, slave relation 1, \(ABN\)000250841
14    False
12    False
dtype: bool

master index 15, slave relation 0, \(NEBIS\)001013464
15     False
145    False
dtype: bool

master index 15, slave relation 1, \(SNL\)vtls000511776
15    False
79    False
dtype: bool

master index 15, slave relation 2, \(Sz\)000511776
15    False
79    False
dtype: bool

master index 16, slave relation 0, \(RERO\)R005694081
16     False
236     True
dtype: bool

master index 16, slave relation 1, \(VAUD\)991003937499702852
16     False
364     True
dtype: bool

master index 16, slave relation 2, \(RNV\)005694081-41bculausa_network
16     False
364     True
dtype: bool

master index 16, slave relation 3, \(RERO\)005694081
16     False
364     True
dtype: bool

master index 16, slave relation 4, R005694081
16     False
236     True
364     True
dtype: bool

master index 16, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991021027629702851
16     False
364     True
dtype: bool

master index 17, slave relation 0, \(IDSBB\)004282572
17     False
125     True
dtype: bool

master index 17, slave relation 1, \(RERO\)R005414091
17     False
235    False
dtype: bool

master index 18, slave relation 0, \(VAUD\)991006920619702852
18     False
383    False
dtype: bool

master index 18, slave relation 1, \(IDSBB\)002886398
18    False
96    False
dtype: bool

master index 18, slave relation 2, \(RNV\)000620926-41bculausa_network
18     False
383    False
dtype: bool

master index 18, slave relation 3, \(RERO\)000620926
18     False
383    False
dtype: bool

master index 18, slave relation 4, 0685929
18     False
383    False
dtype: bool

master index 18, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991020584809702851
18     False
383    False
dtype: bool

master index 19, slave relation 0, \(IDSLU\)001278755
19     False
412    False
dtype: bool

master index 19, slave relation 1, \(SGBN\)000433323
19    False
69    False
dtype: bool

master index 20, slave relation 0, \(RERO\)R007199665
20     False
256    False
dtype: bool

master index 20, slave relation 1, \(IDSBB\)002143345
20     False
106    False
dtype: bool

master index 21, slave relation 0, \(IDSLU\)000434741
21    False
38    False
dtype: bool

master index 21, slave relation 1, \(IDSBB\)002888041
21    False
97    False
dtype: bool

master index 22, slave relation 0, \(RERO\)R248206760
22     False
215     True
dtype: bool

master index 22, slave relation 1, \(IDSBB\)002886399
22     False
102    False
dtype: bool

master index 23, slave relation 0, \(IDSBB\)001975991
23     False
122    False
dtype: bool

master index 23, slave relation 1, \(IDSSG\)000795315
23     False
300    False
dtype: bool

master index 23, slave relation 2, \(IDSLU\)000411402
23    False
28    False
dtype: bool

master index 23, slave relation 3, \(RERO\)R003736670
23     False
224    False
dtype: bool

master index 23, slave relation 4, \(HEMU\)357
23     False
416    False
dtype: bool

master index 24, slave relation 0, \(VAUD\)991019165679702852
24     False
359     True
dtype: bool

master index 24, slave relation 1, \(RERO\)R007095034
24     False
254    False
dtype: bool

master index 24, slave relation 2, \(IDSLU\)000464498
24    False
42    False
dtype: bool

master index 24, slave relation 3, \(RNV\)000396480-41bculausa_network
24     False
359     True
dtype: bool

master index 24, slave relation 4, \(RERO\)000396480
24     False
359     True
dtype: bool

master index 24, slave relation 5, 0429698
24     False
359     True
dtype: bool

master index 24, slave relation 6, \(EXLNZ-41BCULAUSA_NETWORK\)991014527279702851
24     False
359     True
dtype: bool

master index 25, slave relation 0, \(IDSBB\)004231860
25     False
124     True
dtype: bool

master index 25, slave relation 1, \(IDSLU\)000293385
25    False
30    False
dtype: bool

master index 25, slave relation 2, \(NEBIS\)004325390
25     False
158    False
dtype: bool

master index 25, slave relation 3, \(RERO\)0532908
25     False
194    False
dtype: bool

master index 25, slave relation 4, \(VAUD\)991001897789702852
25     False
363    False
dtype: bool

master index 25, slave relation 5, \(ABN\)000728167
25     False
259    False
dtype: bool

master index 25, slave relation 6, \(RNV\)000480336-41bculausa_network
25     False
363    False
dtype: bool

master index 25, slave relation 7, \(RERO\)000480336
25     False
363    False
dtype: bool

master index 25, slave relation 8, 0532908
25     False
194    False
363     True
dtype: bool

master index 25, slave relation 9, \(EXLNZ-41BCULAUSA_NETWORK\)991017164399702851
25     False
363    False
dtype: bool

master index 26, slave relation 0, \(RERO\)1245352
26     False
200     True
dtype: bool

master index 26, slave relation 1, \(VAUD\)991018235149702852
26     False
386     True
dtype: bool

master index 26, slave relation 2, \(RNV\)001137660-41bculausa_network
26     False
386     True
dtype: bool

master index 26, slave relation 3, \(RERO\)001137660
26     False
386     True
dtype: bool

master index 26, slave relation 4, 1245352
26     False
200     True
386     True
dtype: bool

master index 26, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991005861399702851
26     False
386     True
dtype: bool

master index 27, slave relation 0, \(IDSBB\)004385432
27     False
126     True
dtype: bool

master index 27, slave relation 1, \(RERO\)R007160439
27     False
255    False
dtype: bool

master index 28, slave relation 0, \(SNL\)vtls001408718

28    False
89    False
dtype: bool

master index 28, slave relation 1, \(IDSBB\)002136544
28     False
104    False
dtype: bool

master index 28, slave relation 2, \(Sz\)001408718
28    False
89    False
dtype: bool

master index 29, slave relation 0, \(RERO\)R217626960
29     False
211    False
dtype: bool

master index 29, slave relation 1, \(IDSBB\)002136808
29     False
111    False
dtype: bool

master index 29, slave relation 2, \(HEMU\)358
29     False
417    False
dtype: bool

master index 30, slave relation 0, \(RERO\)R005192683
30     False
257    False
dtype: bool

master index 30, slave relation 1, \(IDSBB\)002148277
30     False
113    False
dtype: bool

master index 31, slave relation 0, \(NEBIS\)003645770
31     False
155     True
dtype: bool

master index 31, slave relation 1, \(IDSLU\)000901978
31    False
25    False
dtype: bool

master index 32, slave relation 0, \(RERO\)0429620
32     False
193     True
dtype: bool

master index 32, slave relation 1, \(VAUD\)991019161799702852
32     False
385     True
dtype: bool

master index 32, slave relation 2, \(IDSLU\)000900593
32    False
27    False
dtype: bool

master index 32, slave relation 3, \(RNV\)000396403-41bculausa_network
32     False
385     True
dtype: bool

master index 32, slave relation 4, \(RERO\)000396403
32     False
385     True
dtype: bool

master index 32, slave relation 5, 0429620
32     False
193     True
385     True
dtype: bool

master index 32, slave relation 6, \(EXLNZ-41BCULAUSA_NETWORK\)991014523869702851
32     False
385     True
dtype: bool

master index 33, slave relation 0, \(RERO\)R228487960
33     False
212    False
dtype: bool

master index 33, slave relation 1, \(IDSBB\)002137208
33     False
112    False
dtype: bool

master index 33, slave relation 2, \(IDSLU\)000900603
33    False
40    False
dtype: bool

master index 34, slave relation 0, \(RERO\)R239494260
34     False
213    False
dtype: bool

master index 34, slave relation 1, \(IDSLU\)001139159
34     False
269    False
dtype: bool

master index 34, slave relation 2, \(IDSBB\)002139090
34     False
105    False
dtype: bool

master index 35, slave relation 0, \(NEBIS\)004327684
35     False
157    False
dtype: bool

master index 35, slave relation 1, \(HEMU\)9473
35     False
419    False
dtype: bool

master index 36, slave relation 0, \(RERO\)1553447
36     False
207     True
dtype: bool

master index 36, slave relation 1, \(VAUD\)991002507509702852
36     False
370     True
dtype: bool

master index 36, slave relation 2, \(RNV\)001419203-41bculausa_network
36     False
370     True
dtype: bool

master index 36, slave relation 3, \(RERO\)001419203
36     False
370     True
dtype: bool

master index 36, slave relation 4, 1553447
36     False
207     True
370     True
dtype: bool

master index 36, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991009739879702851
36     False
370     True
dtype: bool

master index 37, slave relation 0, \(NEBIS\)005802053
37     False
171     True
dtype: bool

master index 37, slave relation 1, \(RERO\)R003755591
37     False
225    False
dtype: bool

master index 38, slave relation 0, \(IDSLU\)000489765
38    False
26     True
dtype: bool

master index 38, slave relation 1, \(BGR\)000119170
38    False
20    False
dtype: bool

master index 38, slave relation 2, \(IDSBB\)005967090
38     False
116    False
dtype: bool

master index 38, slave relation 3, \(RERO\)R006457716
38     False
248    False
dtype: bool

master index 39, slave relation 0, \(ABN\)000234417
39    False
6      True
dtype: bool

master index 39, slave relation 1, \(RERO\)R004065622
39     False
230    False
dtype: bool

master index 40, slave relation 0, \(VAUD\)991002453359702853
40     False
393     True
dtype: bool

master index 40, slave relation 1, \(RERO\)R006492170
40     False
251    False
dtype: bool

master index 40, slave relation 2, \(RNV\)007446856-41bculausa_network
40     False
393     True
dtype: bool

master index 40, slave relation 3, \(RERO\)007446856
40     False
393     True
dtype: bool

master index 40, slave relation 4, R007446856
40     False
393     True
dtype: bool

master index 40, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991011579199702851
40     False
393     True
dtype: bool

master index 41, slave relation 0, \(IDSLU\)000296294
41    False
24     True
dtype: bool

master index 41, slave relation 1, \(NEBIS\)001183345
41     False
146    False
dtype: bool

master index 41, slave relation 2, \(SBT\)000242507
41    False
58    False
dtype: bool

master index 42, slave relation 0, \(IDSBB\)006087590
42     False
136     True
dtype: bool

master index 42, slave relation 1, \(IDSLU\)001183923
42     False
283     True
dtype: bool

master index 42, slave relation 2, \(RERO\)R006459686
42     False
249    False
dtype: bool

master index 43, slave relation 0, \(BGR\)000107522
43    False
16     True
dtype: bool

master index 43, slave relation 1, \(RERO\)R006468090
43     False
250    False
dtype: bool

master index 44, slave relation 0, \(RERO\)R006127559
44     False
240    False
dtype: bool

master index 44, slave relation 1, \(RERO\)R275505960
44     False
219    False
dtype: bool

master index 45, slave relation 0, \(RERO\)R008100270
45     False
285     True
dtype: bool

master index 45, slave relation 1, \(SGBN\)000329876
45    False
72    False
dtype: bool

master index 46, slave relation 0, \(IDSLU\)000438850
46    False
23    False
dtype: bool

master index 46, slave relation 1, \(RERO\)R006336083
46     False
247    False
dtype: bool

master index 47, slave relation 0, \(IDSLU\)000181515
47    False
33     True
dtype: bool

master index 47, slave relation 1, \(IDSBB\)000044352
47     False
120    False
dtype: bool

master index 47, slave relation 2, \(NEBIS\)008941219
47     False
181    False
dtype: bool

master index 48, slave relation 0, \(IDSBB\)002078403
48     False
138    False
dtype: bool

master index 48, slave relation 1, \(NEBIS\)005266910
48     False
190    False
dtype: bool

master index 48, slave relation 2, \(IDSLU\)000313598
48    False
46    False
dtype: bool

master index 48, slave relation 3, \(KBTG\)128844
48     False
432    False
dtype: bool

master index 48, slave relation 4, \(RERO\)R280794460
48     False
221    False
dtype: bool

master index 49, slave relation 0, \(RERO\)R006132598
49     False
241    False
dtype: bool

master index 49, slave relation 1, \(RERO\)R275508860
49     False
220    False
dtype: bool

master index 50, slave relation 0, \(RERO\)1543180
50     False
202     True
dtype: bool

master index 50, slave relation 1, \(VAUD\)991002343679702852
50     False
402     True
dtype: bool

master index 50, slave relation 2, \(RNV\)001409827-41bculausa_network
50     False
402     True
dtype: bool

master index 50, slave relation 3, \(RERO\)001409827
50     False
402     True
dtype: bool

master index 50, slave relation 4, 1543180
50     False
202     True
402     True
dtype: bool

master index 50, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991009628379702851
50     False
402     True
dtype: bool

master index 51, slave relation 0, \(SNL\)vtls001337152
51    False
88     True
dtype: bool

master index 51, slave relation 1, \(SGBN\)000393754
51    False
63    False
dtype: bool

master index 51, slave relation 2, \(Sz\)001337152
51    False
88     True
dtype: bool

master index 52, slave relation 0, \(NEBIS\)003169768
52     False
153     True
dtype: bool

master index 52, slave relation 1, \(IDSBB\)002888097
52    False
98    False
dtype: bool

master index 53, slave relation 0, \(NEBIS\)010817639
53     False
405     True
dtype: bool

master index 53, slave relation 1, \(IDSBB\)005193082
53    False
99     True
dtype: bool

master index 54, slave relation 0, \(RERO\)1706143
54     False
209     True
dtype: bool

master index 54, slave relation 1, \(NEBIS\)009407654
54     False
183    False
dtype: bool

master index 54, slave relation 2, \(IDSBB\)002888123
54     False
101    False
dtype: bool

master index 54, slave relation 3, \(RERO\)R006024330
54     False
238    False
dtype: bool

master index 55, slave relation 0, \(IDSLU\)000914856
55    False
35     True
dtype: bool

master index 55, slave relation 1, \(NEBIS\)003345899
55     False
154    False
dtype: bool

master index 55, slave relation 2, \(SGBN\)001042825
55    False
67    False
dtype: bool

master index 55, slave relation 3, \(OCoLC\)695891867
55     False
35      True
67     False
154    False
dtype: bool

master index 56, slave relation 0, \(RERO\)R007813227
56     False
273     True
dtype: bool

master index 56, slave relation 1, \(NEBIS\)006439592
56     False
173    False
dtype: bool

master index 56, slave relation 2, \(OCoLC\)314032386
56     False
173    False
dtype: bool

master index 57, slave relation 0, \(IDSBB\)004654810
57     False
137     True
dtype: bool

master index 57, slave relation 1, \(ABN\)000223912
57    False
3     False
dtype: bool

master index 58, slave relation 0, \(NEBIS\)004978245
58     False
161     True
dtype: bool

master index 58, slave relation 1, \(SGBN\)001013366
58    False
68     True
dtype: bool

master index 59, slave relation 0, \(IDSLU\)000853899
59    False
34     True
dtype: bool

master index 59, slave relation 1, \(RERO\)R006024329
59     False
237    False
dtype: bool

master index 60, slave relation 0, \(RERO\)1245494
60     False
201     True
dtype: bool

master index 60, slave relation 1, \(VAUD\)991018237399702852
60     False
399     True
dtype: bool

master index 60, slave relation 2, \(RNV\)001137782-41bculausa_network
60     False
399     True
dtype: bool

master index 60, slave relation 3, \(RERO\)001137782
60     False
399     True
dtype: bool

master index 60, slave relation 4, 1245494
60     False
201     True
399     True
dtype: bool

master index 60, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991005863319702851

60     False
399     True
dtype: bool

master index 61, slave relation 0, \(IDSBB\)001255067
61    False
95     True
dtype: bool

master index 61, slave relation 1, \(NEBIS\)011007027
61     False
426     True
dtype: bool

master index 62, slave relation 0, \(IDSBB\)002888099
62     False
100     True
dtype: bool

master index 62, slave relation 1, \(SGBN\)000547881
62    False
66    False
dtype: bool

master index 63, slave relation 0, \(IDSBB\)002888113
63     False
110     True
dtype: bool

master index 63, slave relation 1, \(NEBIS\)009960379
63     False
260    False
dtype: bool

master index 64, slave relation 0, \(SGBN\)001262318
64     False
266    False
dtype: bool

master index 64, slave relation 1, \(RERO\)R007560941
64     False
265    False
dtype: bool

master index 65, slave relation 0, \(RERO\)1553399
65     False
203     True
dtype: bool

master index 65, slave relation 1, \(SNL\)vtls000622834
65    False
83    False
dtype: bool

master index 65, slave relation 2, \(Sz\)000622834
65    False
83    False
dtype: bool

master index 66, slave relation 0, \(RERO\)1553409
66     False
204     True
dtype: bool

master index 66, slave relation 1, \(VAUD\)991002506909702852
66     False
366     True
dtype: bool

master index 66, slave relation 2, \(RNV\)001419170-41bculausa_network
66     False
366     True
dtype: bool

master index 66, slave relation 3, \(RERO\)001419170
66     False
366     True
dtype: bool

master index 66, slave relation 4, 1553409
66     False
204     True
366     True
dtype: bool

master index 66, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991009739479702851
66     False
366     True
dtype: bool

master index 67, slave relation 0, \(SGBN\)000542763
67    False
65    False
dtype: bool

master index 67, slave relation 1, \(RERO\)1553417
67     False
205    False
dtype: bool

master index 68, slave relation 0, \(NEBIS\)000013680
68     False
143    False
dtype: bool

master index 68, slave relation 1, \(SBT\)000288262
68    False
54    False
dtype: bool

master index 69, slave relation 0, \(RERO\)1245069
69     False
197     True
dtype: bool

master index 69, slave relation 1, \(VAUD\)991018231439702852
69     False
400     True
dtype: bool

master index 69, slave relation 2, \(RNV\)001137451-41bculausa_network
69     False
400     True
dtype: bool

master index 69, slave relation 3, \(RERO\)001137451
69     False
400     True
dtype: bool

master index 69, slave relation 4, 1245069
69     False
197     True
400     True
dtype: bool

master index 69, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991005858089702851
69     False
400     True
dtype: bool

master index 70, slave relation 0, \(RERO\)R006145307
70     False
242     True
dtype: bool

master index 70, slave relation 1, \(VAUD\)991001903539702853
70     False
394     True
dtype: bool

master index 70, slave relation 2, \(RERO\)1245333
70     False
199     True
dtype: bool

master index 70, slave relation 3, \(VAUD\)991018235049702852
70     False
379     True
dtype: bool

master index 70, slave relation 4, \(RNV\)006145307-41bculausa_network
70     False
394     True
dtype: bool

master index 70, slave relation 5, \(RERO\)006145307
70     False
394     True
dtype: bool

master index 70, slave relation 6, R006145307
70     False
242     True
394     True
dtype: bool

master index 70, slave relation 7, \(EXLNZ-41BCULAUSA_NETWORK\)991005167179702851
70     False
394     True
dtype: bool

master index 70, slave relation 8, \(RNV\)001137656-41bculausa_network
70     False
379     True
dtype: bool

master index 70, slave relation 9, \(RERO\)001137656
70     False
379     True
dtype: bool

master index 70, slave relation 10, 1245333
70     False
199     True
379     True
dtype: bool

master index 70, slave relation 11, \(EXLNZ-41BCULAUSA_NETWORK\)991005861309702851
70     False
379     True
dtype: bool

master index 71, slave relation 0, \(RERO\)R006172599
71     False
244     True
dtype: bool

master index 71, slave relation 1, \(RERO\)R275502460
71     False
218    False
dtype: bool

master index 72, slave relation 0, \(RERO\)R006145310
72     False
243     True
dtype: bool

master index 72, slave relation 1, \(RERO\)1245332
72     False
198    False
dtype: bool

master index 72, slave relation 2, \(VAUD\)991018235009702852
72     False
387    False
dtype: bool

master index 72, slave relation 3, \(RNV\)001137655-41bculausa_network
72     False
387    False
dtype: bool

master index 72, slave relation 4, \(RERO\)001137655
72     False
387    False
dtype: bool

master index 72, slave relation 5, 1245332
72     False
198    False
387     True
dtype: bool

master index 72, slave relation 6, \(EXLNZ-41BCULAUSA_NETWORK\)991005861269702851
72     False
387    False
dtype: bool

master index 73, slave relation 0, \(RERO\)R003834746
73     False
227     True
dtype: bool

master index 73, slave relation 1, \(SNL\)vtls000622832
73    False
81    False
dtype: bool

master index 73, slave relation 2, \(Sz\)000622832
73    False
81    False
dtype: bool

master index 74, slave relation 0, \(IDSBB\)006503313
74     False
325     True
dtype: bool

master index 74, slave relation 1, \(IDSBB\)006491015
74     False
326    False
dtype: bool

master index 74, slave relation 2, \(SNL\)vtls001808557
74     False
317    False
dtype: bool

master index 74, slave relation 3, \(Sz\)001808557
74     False
317    False
dtype: bool

master index 75, slave relation 0, \(IDSBB\)006000910
75     False
330    False
dtype: bool

master index 75, slave relation 1, \(ABN\)000817339
75     False
431    False
dtype: bool

master index 75, slave relation 2, \(ALEX\)993884634101791
75     False
308    False
dtype: bool

master index 76, slave relation 0, \(IDSBB\)003619958
76     False
114    False
dtype: bool

master index 76, slave relation 1, \(NEBIS\)004858174
76     False
159    False
dtype: bool

master index 76, slave relation 2, \(ALEX\)993842134101791
76     False
305    False
dtype: bool

master index 76, slave relation 3, \(SNL\)vtls001499826
76    False
90    False
dtype: bool

master index 76, slave relation 4, \(VAUD\)991017059359702852
76     False
381    False
dtype: bool

master index 76, slave relation 5, \(Sz\)001499826
76    False
90    False
dtype: bool

master index 76, slave relation 6, \(RNV\)000343919-41bculausa_network
76     False
381    False
dtype: bool

master index 76, slave relation 7, \(RERO\)000343919
76     False
381    False
dtype: bool

master index 76, slave relation 8, 0372472
76     False
381    False
dtype: bool

master index 76, slave relation 9, \(EXLNZ-41BCULAUSA_NETWORK\)991012829779702851
76     False
381    False
dtype: bool

master index 77, slave relation 0, \(IDSBB\)006573712
77     False
329    False
dtype: bool

master index 77, slave relation 1, \(IDSLU\)000546873
77    False
32    False
dtype: bool

master index 78, slave relation 0, \(IDSBB\)004969781
78     False
140     True
dtype: bool

master index 78, slave relation 1, \(NEBIS\)009471728
78     False
185    False
dtype: bool

master index 79, slave relation 0, \(SNL\)vtls000054454
79    False
78     True
dtype: bool

master index 79, slave relation 1, \(NEBIS\)000980653
79     False
144    False
dtype: bool

master index 79, slave relation 2, \(IDSLU\)000194125
79    False
41    False
dtype: bool

master index 79, slave relation 3, \(ABN\)000048149
79    False
8     False
dtype: bool

master index 79, slave relation 4, \(BGR\)000009742
79    False
18    False
dtype: bool

master index 79, slave relation 5, \(SGBN\)000007701
79    False
62    False
dtype: bool

master index 79, slave relation 6, \(IDSBB\)000193942
79     False
281    False
dtype: bool

master index 79, slave relation 7, \(IDSSG\)000724644
79     False
296    False
dtype: bool

master index 79, slave relation 8, \(Sz\)000054454
79    False
78     True
dtype: bool

master index 79, slave relation 9, \(OCoLC\)630213725
79     False
296    False
dtype: bool

master index 80, slave relation 0, \(IDSBB\)006244427
80     False
270    False
dtype: bool

master index 80, slave relation 1, \(NEBIS\)010617336
80     False
318    False
dtype: bool

master index 80, slave relation 2, \(SGBN\)001348003
80     False
314    False
dtype: bool

master index 81, slave relation 0, \(IDSBB\)006726594
81     False
424     True
dtype: bool

master index 81, slave relation 1, \(NEBIS\)011045420
81     False
428     True
dtype: bool

master index 81, slave relation 2, \(OCoLC\)1002177443
81     False
424     True
428     True
dtype: bool

master index 82, slave relation 0, \(IDSSG\)000834462
82     False
302     True
dtype: bool

master index 82, slave relation 1, \(IDSBB\)006167137
82     False
261    False
dtype: bool

master index 82, slave relation 2, \(IDSLU\)001243326
82     False
327    False
dtype: bool

master index 82, slave relation 3, \(NEBIS\)009977810
82     False
263    False
dtype: bool

master index 82, slave relation 4, \(BGR\)000666727
82     False
350    False
dtype: bool

master index 82, slave relation 5, \(OCoLC\)856595678
82     False
261    False
263    False
302     True
327    False
dtype: bool

master index 82, slave relation 6, \(DE-599\)DNB1036279944
82     False
327    False
dtype: bool

master index 83, slave relation 0, \(IDSBB\)002281367
83     False
127     True
dtype: bool

master index 83, slave relation 1, \(NEBIS\)008641750
83     False
180    False
dtype: bool

master index 83, slave relation 2, \(RERO\)R003530696
83     False
223    False
dtype: bool

master index 83, slave relation 3, \(ALEX\)9912420374101791
83     False
306    False
dtype: bool

master index 84, slave relation 0, \(NEBIS\)009226253
84     False
182     True
dtype: bool

master index 84, slave relation 1, \(IDSBB\)003577580
84     False
128    False
dtype: bool

master index 84, slave relation 2, \(DDB\)972604650
84     False
128    False
dtype: bool

master index 85, slave relation 0, \(NEBIS\)009587153
85     False
187     True
dtype: bool

master index 85, slave relation 1, \(LIBIB\)000315536
85     False
276     True
dtype: bool

master index 85, slave relation 2, \(ABN\)000539983
85    False
0     False
dtype: bool

master index 86, slave relation 0, \(NEBIS\)008647887
86     False
179     True
dtype: bool

master index 86, slave relation 1, \(VAUD\)991001434509702852
86     False
378    False
dtype: bool

master index 86, slave relation 2, \(RNV\)003104061-41bculausa_network
86     False
378    False
dtype: bool

master index 86, slave relation 3, \(RERO\)003104061
86     False
378    False
dtype: bool

master index 86, slave relation 4, R003104061
86     False
378    False
dtype: bool

master index 86, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991001405619702851
86     False
378    False

dtype: bool

master index 87, slave relation 0, \(IDSLU\)000449481
87    False
29    False
dtype: bool

master index 87, slave relation 1, \(IDSBB\)003781869
87     False
130    False
dtype: bool

master index 87, slave relation 2, \(NEBIS\)004930649
87     False
160    False
dtype: bool

master index 87, slave relation 3, \(IDSSG\)000338145
87    False
51    False
dtype: bool

master index 87, slave relation 4, \(BGR\)000463276
87    False
19    False
dtype: bool

master index 87, slave relation 5, \(RERO\)R003971490
87     False
229    False
dtype: bool

master index 87, slave relation 6, \(VAUD\)991010949619702852
87     False
373    False
dtype: bool

master index 87, slave relation 7, \(RNV\)003971490-41bculausa_network
87     False
373    False
dtype: bool

master index 87, slave relation 8, \(RERO\)003971490
87     False
373    False
dtype: bool

master index 87, slave relation 9, R003971490
87     False
229    False
373     True
dtype: bool

master index 87, slave relation 10, \(EXLNZ-41BCULAUSA_NETWORK\)991008949409702851
87     False
373    False
dtype: bool

master index 88, slave relation 0, \(SGBN\)001068279
88    False
77     True
dtype: bool

master index 88, slave relation 1, \(ABN\)000548154
88    False
4     False
dtype: bool

master index 88, slave relation 2, \(BGR\)000409509
88    False
17    False
dtype: bool

master index 88, slave relation 3, \(NEBIS\)005724810
88     False
170    False
dtype: bool

master index 88, slave relation 4, \(OCoLC\)495204467
88    False
77     True
dtype: bool

master index 89, slave relation 0, \(IDSBB\)001470548
89     False
109     True
dtype: bool

master index 89, slave relation 1, \(SGBN\)001344510
89     False
311    False
dtype: bool

master index 90, slave relation 0, \(RERO\)0277119
90     False
192     True
dtype: bool

master index 90, slave relation 1, \(VAUD\)991012920519702852
90     False
367     True
dtype: bool

master index 90, slave relation 2, \(SBT\)000063646
90    False
61     True
dtype: bool

master index 90, slave relation 3, \(RNV\)000256377-41bculausa_network
90     False
367     True
dtype: bool

master index 90, slave relation 4, \(RERO\)000256377
90     False
367     True
dtype: bool

master index 90, slave relation 5, 0277119
90     False
192     True
367     True
dtype: bool

master index 90, slave relation 6, \(EXLNZ-41BCULAUSA_NETWORK\)991009487549702851
90     False
367     True
dtype: bool

master index 91, slave relation 0, \(SERSOL\)ssj0001187843
91     False
335     True
dtype: bool

master index 91, slave relation 1, \(IDSLU\)001167857
91     False
279    False
dtype: bool

master index 91, slave relation 2, \(NEBIS\)010141085
91     False
271    False
dtype: bool

master index 91, slave relation 3, \(WaSeSS\)ssj0001187843
91     False
335     True
dtype: bool

master index 92, slave relation 0, \(IDSBB\)006207118
92     False
267     True
dtype: bool

master index 92, slave relation 1, \(NEBIS\)010150430
92     False
272    False
dtype: bool

master index 92, slave relation 2, \(RERO\)R008122523
92     False
286    False
dtype: bool

master index 92, slave relation 3, \(IDSSG\)000839244
92     False
303    False
dtype: bool

master index 92, slave relation 4, \(DE-599\)DNB104479352X
92     False
267     True
dtype: bool

master index 92, slave relation 5, \(OCoLC\)871188367
92     False
267     True
272    False
303    False
dtype: bool

master index 93, slave relation 0, \(SNL\)vtls001809361
93     False
320    False
dtype: bool

master index 93, slave relation 1, \(IDSBB\)006499413
93     False
323    False
dtype: bool

master index 93, slave relation 2, \(IDSBB\)006491076
93     False
322    False
dtype: bool

master index 93, slave relation 3, \(Sz\)001809361
93     False
320    False
dtype: bool

master index 94, slave relation 0, \(IDSBB\)006040856
94     False
129    False
dtype: bool

master index 94, slave relation 1, \(NEBIS\)001874887
94     False
149    False
dtype: bool

master index 95, slave relation 0, \(IDSLU\)000932524
95    False
36     True
dtype: bool

master index 95, slave relation 1, \(NEBIS\)009631799
95     False
188    False
dtype: bool

master index 95, slave relation 2, \(OCoLC\)666982244
95     False
36      True
188    False
dtype: bool

master index 96, slave relation 0, \(NEBIS\)010611165
96     False
316     True
dtype: bool

master index 96, slave relation 1, \(ABN\)000781689
96     False
289    False
dtype: bool

master index 96, slave relation 2, \(OCoLC\)913607514
96     False
289    False
316     True
dtype: bool

master index 97, slave relation 0, \(SNL\)vtls001860441
97     False
353     True
dtype: bool

master index 97, slave relation 1, \(SNL\)vtls001860442
97     False
354    False
dtype: bool

master index 97, slave relation 2, \(Sz\)001860441
97     False
353     True
dtype: bool

master index 97, slave relation 3, \(Sz\)001860442
97     False
354    False
dtype: bool

master index 98, slave relation 0, \(SNL\)vtls001887658
98     False
408     True
dtype: bool

master index 98, slave relation 1, \(SNL\)vtls001887659
98     False
409    False
dtype: bool

master index 98, slave relation 2, \(Sz\)001887658
98     False
408     True
dtype: bool

master index 98, slave relation 3, \(Sz\)001887659
98     False
409    False
dtype: bool

master index 99, slave relation 0, \(SNL\)vtls001860440
99     False
352     True
dtype: bool

master index 99, slave relation 1, \(SNL\)vtls001860448
99     False
357    False
dtype: bool

master index 99, slave relation 2, \(Sz\)001860440
99     False
352     True
dtype: bool

master index 99, slave relation 3, \(Sz\)001860448
99     False
357    False
dtype: bool

master index 100, slave relation 0, \(SNL\)vtls001860443
100    False
355     True
dtype: bool

master index 100, slave relation 1, \(SNL\)vtls001860444
100    False
356    False
dtype: bool

master index 100, slave relation 2, \(Sz\)001860443
100    False
355     True
dtype: bool

master index 100, slave relation 3, \(Sz\)001860444
100    False
356    False
dtype: bool

master index 101, slave relation 0, \(SNL\)vtls001092110
101    False
84      True
dtype: bool

master index 101, slave relation 1, \(NEBIS\)001565054
101    False
148    False
dtype: bool

master index 101, slave relation 2, \(Sz\)001092110
101    False
84      True
dtype: bool

master index 102, slave relation 0, \(SNL\)vtls001866899
102    False
388     True
dtype: bool

master index 102, slave relation 1, \(SNL\)vtls001866900
102    False
389    False
dtype: bool

master index 102, slave relation 2, \(Sz\)001866899
102    False
388     True
dtype: bool

master index 102, slave relation 3, \(Sz\)001866900
102    False
389    False
dtype: bool

master index 103, slave relation 0, \(SNL\)vtls001866901
103    False
390     True
dtype: bool

master index 103, slave relation 1, \(SNL\)vtls001866902
103    False
391    False
dtype: bool

master index 103, slave relation 2, \(Sz\)001866901
103    False
390     True
dtype: bool

master index 103, slave relation 3, \(Sz\)001866902
103    False
391    False
dtype: bool

master index 104, slave relation 0, \(SNL\)vtls001887640
104    False
407     True
dtype: bool

master index 104, slave relation 1, \(SNL\)vtls001887704
104    False
410    False
dtype: bool

master index 104, slave relation 2, \(Sz\)001887640
104    False
407     True
dtype: bool

master index 104, slave relation 3, \(Sz\)001887704
104    False
410    False
dtype: bool

master index 105, slave relation 0, \(SNL\)vtls001852008
105    False
343     True
dtype: bool

master index 105, slave relation 1, \(SNL\)vtls001851938
105    False
337     True
dtype: bool

master index 105, slave relation 2, \(Sz\)001852008
105    False
343     True
dtype: bool

master index 105, slave relation 3, \(Sz\)001851938
105    False
337     True
dtype: bool

master index 106, slave relation 0, \(SNL\)vtls001851966
106    False
338     True
dtype: bool

master index 106, slave relation 1, \(SNL\)vtls001852007
106    False
342     True
dtype: bool

master index 106, slave relation 2, \(Sz\)001851966
106    False
338     True
dtype: bool

master index 106, slave relation 3, \(Sz\)001852007
106    False
342     True
dtype: bool

master index 107, slave relation 0, \(SNL\)vtls001851968
107    False
339     True
dtype: bool

master index 107, slave relation 1, \(SNL\)vtls001852009
107    False
344     True
dtype: bool

master index 107, slave relation 2, \(Sz\)001851968
107    False
339     True
dtype: bool

master index 107, slave relation 3, \(Sz\)001852009
107    False
344     True
dtype: bool

master index 108, slave relation 0, \(SNL\)vtls001852003
108    False
340     True
dtype: bool

master index 108, slave relation 1, \(SNL\)vtls001852005
108    False
341     True
dtype: bool

master index 108, slave relation 2, \(Sz\)001852003
108    False
340     True
dtype: bool

master index 108, slave relation 3, \(Sz\)001852005
108    False
341     True
dtype: bool

master index 109, slave relation 0, \(IDSLU\)000093757
109    False
43      True
dtype: bool

master index 109, slave relation 1, \(NEBIS\)002041247
109    False
151    False
dtype: bool

master index 110, slave relation 0, \(IDSBB\)001616721
110    False
134    False
dtype: bool

master index 110, slave relation 1, \(BGR\)000141165
110    False
22     False
dtype: bool

master index 110, slave relation 2, \(SNL\)vtls001191253
110    False
85     False
dtype: bool

master index 110, slave relation 3, \(RERO\)R256033860
110    False
216    False
dtype: bool

master index 110, slave relation 4, \(Sz\)001191253
110    False
85     False
dtype: bool

master index 111, slave relation 0, \(RERO\)2154763
111    False
210    False
dtype: bool

master index 111, slave relation 1, \(SBT\)000356823
111    False
55     False
dtype: bool

master index 112, slave relation 0, \(NEBIS\)005997889
112    False
172     True
dtype: bool

master index 112, slave relation 1, \(IDSBB\)004783884
112    False
139    False

dtype: bool

master index 112, slave relation 2, \(IDSSG\)000800002
112    False
301    False
dtype: bool

master index 112, slave relation 3, \(ABN\)000758696
112    False
332    False
dtype: bool

master index 112, slave relation 4, \(SGBN\)001031594
112    False
71     False
dtype: bool

master index 112, slave relation 5, \(BGR\)000540258
112    False
268    False
dtype: bool

master index 113, slave relation 0, \(NATIONALLICENCE\)oxford-10.1093/cid/cir669
113    False
348    False
dtype: bool

master index 113, slave relation 1, \(ZORA\)oai:www.zora.uzh.ch:53042
113    False
258    False
dtype: bool

master index 113, slave relation 2, \(SERVAL\)BIB_124AC4C289C2
113    False
277    False
dtype: bool

master index 114, slave relation 0, \(BGR\)000647732
114    False
310     True
dtype: bool

master index 114, slave relation 1, \(IDSBB\)006022532
114    False
118    False
dtype: bool

master index 114, slave relation 2, \(NEBIS\)006483696
114    False
174    False
dtype: bool

master index 114, slave relation 3, \(OCoLC\)731676557
114    False
118    False
310     True
dtype: bool

master index 114, slave relation 4, \(OCoLC\)725111700
114    False
174    False
dtype: bool

master index 115, slave relation 0, \(IDSSG\)000785108
115    False
299    False
dtype: bool

master index 115, slave relation 1, \(ABN\)000308006
115    False
5      False
dtype: bool

master index 115, slave relation 2, \(RERO\)R006197994
115    False
245    False
dtype: bool

master index 115, slave relation 3, \(IDSBB\)004181136
115    False
141    False
dtype: bool

master index 115, slave relation 4, \(NEBIS\)005482185
115    False
165    False
dtype: bool

master index 116, slave relation 0, \(NEBIS\)001584785
116    False
147    False
dtype: bool

master index 116, slave relation 1, \(IDSBB\)001974245
116    False
103    False
dtype: bool

master index 117, slave relation 0, \(RERO\)R004091898
117    False
231     True
dtype: bool

master index 117, slave relation 1, \(VAUD\)991011403159702852
117    False
376     True
dtype: bool

master index 117, slave relation 2, \(VAUD\)991001046399702853
117    False
392     True
dtype: bool

master index 117, slave relation 3, \(RNV\)004091898-41bculausa_network
117    False
376     True
392     True
dtype: bool

master index 117, slave relation 4, \(RERO\)004091898
117    False
376     True
392     True
dtype: bool

master index 117, slave relation 5, R004091898
117    False
231     True
376     True
392     True
dtype: bool

master index 117, slave relation 6, \(EXLNZ-41BCULAUSA_NETWORK\)991009328189702851
117    False
376     True
392     True
dtype: bool

master index 118, slave relation 0, \(RERO\)1553441
118    False
206     True
dtype: bool

master index 118, slave relation 1, \(VAUD\)991002507429702852
118    False
382     True
dtype: bool

master index 118, slave relation 2, \(RNV\)001419197-41bculausa_network
118    False
382     True
dtype: bool

master index 118, slave relation 3, \(RERO\)001419197
118    False
382     True
dtype: bool

master index 118, slave relation 4, 1553441
118    False
206     True
382     True
dtype: bool

master index 118, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991009739809702851
118    False
382     True
dtype: bool

master index 119, slave relation 0, \(IDSBB\)001651899
119    False
121    False
dtype: bool

master index 119, slave relation 1, \(NEBIS\)001974886
119    False
150    False
dtype: bool

master index 119, slave relation 2, \(IDSSG\)000177847
119    False
53     False
dtype: bool

master index 119, slave relation 3, \(SGBN\)000249023
119    False
73     False
dtype: bool

master index 119, slave relation 4, \(SNL\)vtls001203051
119    False
86     False
dtype: bool

master index 119, slave relation 5, \(IDSLU\)000164505
119    False
48     False
dtype: bool

master index 119, slave relation 6, \(RERO\)R243599160
119    False
214    False
dtype: bool

master index 119, slave relation 7, \(VAUD\)991016630449702852
119    False
398    False
dtype: bool

master index 119, slave relation 8, \(ABN\)000096920
119    False
2      False
dtype: bool

master index 119, slave relation 9, \(Sz\)001203051
119    False
86     False
dtype: bool

master index 119, slave relation 10, \(RNV\)002435991-41bculausa_network
119    False
398    False
dtype: bool

master index 119, slave relation 11, \(RERO\)002435991
119    False
398    False
dtype: bool

master index 119, slave relation 12, R243599160
119    False
214    False
398     True
dtype: bool

master index 119, slave relation 13, \(EXLNZ-41BCULAUSA_NETWORK\)991020678209702851
119    False
398    False
dtype: bool

master index 120, slave relation 0, \(IDSBB\)006497028
120    False
321    False
dtype: bool

master index 120, slave relation 1, \(BGR\)000663107
120    False
334    False
dtype: bool

master index 120, slave relation 2, \(SNL\)vtls001800340
120    False
328    False
dtype: bool

master index 120, slave relation 3, \(RERO\)R008423710
120    False
324    False
dtype: bool

master index 120, slave relation 4, \(DE-599\)DNB1079543961
120    False
321    False
dtype: bool

master index 120, slave relation 5, \(OCoLC\)932026571
120    False
321    False
dtype: bool

master index 120, slave relation 6, \(Sz\)001800340
120    False
328    False
dtype: bool

master index 121, slave relation 0, \(RERO\)R008499625
121    False
358     True
dtype: bool

master index 121, slave relation 1, \(NEBIS\)010734165
121    False
346    False
dtype: bool

master index 121, slave relation 2, \(BGR\)000660651
121    False
345    False
dtype: bool

master index 121, slave relation 3, \(ABN\)000804056
121    False
351    False
dtype: bool

master index 121, slave relation 4, \(OCoLC\)951113986
121    False
346    False
351    False
dtype: bool

master index 122, slave relation 0, \(SNL\)vtls001889387
122    False
411    False
dtype: bool

master index 122, slave relation 1, \(KBTG\)263228
122    False
434    False
dtype: bool

master index 122, slave relation 2, \(Sz\)001889387
122    False
411    False
dtype: bool

master index 123, slave relation 0, \(RERO\)0209667
123    False
191     True
dtype: bool

master index 123, slave relation 1, \(VAUD\)991010321879702852
123    False
429     True
dtype: bool

master index 123, slave relation 2, \(RNV\)000202321-41bculausa_network
123    False
429     True
dtype: bool

master index 123, slave relation 3, \(RERO\)000202321
123    False
429     True
dtype: bool

master index 123, slave relation 4, 0209667
123    False
191     True
429     True
dtype: bool

master index 123, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991007433319702851
123    False
429     True
dtype: bool

master index 124, slave relation 0, \(RERO\)R007822798
124    False
293     True
dtype: bool

master index 124, slave relation 1, \(VAUD\)991000042089702852
124    False
361     True
dtype: bool

master index 124, slave relation 2, \(RNV\)007822798-41bculausa_network
124    False
361     True
dtype: bool

master index 124, slave relation 3, \(RERO\)007822798
124    False
361     True
dtype: bool

master index 124, slave relation 4, R007822798
124    False
293     True
361     True
dtype: bool

master index 124, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991014602959702851
124    False
361     True
dtype: bool

master index 125, slave relation 0, \(LIBIB\)000378731
125    False
291     True
dtype: bool

master index 125, slave relation 1, \(SBT\)000766642
125    False
295    False
dtype: bool

master index 126, slave relation 0, \(RERO\)R008488254
126    False
331     True
dtype: bool

master index 126, slave relation 1, \(VAUD\)991021085980402852
126    False
371     True
dtype: bool

master index 126, slave relation 2, \(VAUD\)991002785558502853
126    False
395     True
dtype: bool

master index 126, slave relation 3, \(EXLNZ-41BCULAUSA_NETWORK\)991023401938902851
126    False
371     True
395     True
dtype: bool

master index 127, slave relation 0, \(VAUD\)991002788050002853
127    False
396     True
dtype: bool

master index 127, slave relation 1, \(RERO\)R008564996
127    False
403    False
dtype: bool

master index 127, slave relation 2, \(EXLNZ-41BCULAUSA_NETWORK\)991023407615802851
127    False
396     True
dtype: bool

master index 128, slave relation 0, \(RERO\)1555485
128    False
208     True
dtype: bool

master index 128, slave relation 1, \(VAUD\)991002545759702852
128    False
365     True
dtype: bool

master index 128, slave relation 2, \(RNV\)001421044-41bculausa_network
128    False
365     True
dtype: bool

master index 128, slave relation 3, \(RERO\)001421044
128    False
365     True
dtype: bool

master index 128, slave relation 4, 1555485
128    False
208     True
365     True
dtype: bool

master index 128, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991009765369702851
128    False
365     True
dtype: bool

master index 129, slave relation 0, \(NEBIS\)007244145
129    False
178     True
dtype: bool

master index 129, slave relation 1, \(SGBN\)001351177
129    False
430    False
dtype: bool

master index 130, slave relation 0, \(IDSLU\)000503700
130    False
37      True
dtype: bool

master index 130, slave relation 1, \(NEBIS\)005540513
130    False
166    False
dtype: bool

master index 130, slave relation 2, \(RERO\)R004272337
130    False
233    False
dtype: bool

master index 130, slave relation 3, \(IDSBB\)005975902
130    False
142    False
dtype: bool

master index 130, slave relation 4, \(LIBIB\)000256201
130    False
275    False
dtype: bool

master index 130, slave relation 5, \(IDSSG\)000780032
130    False
298    False
dtype: bool

master index 130, slave relation 6, \(SGBN\)001196568
130    False
319    False
dtype: bool

master index 130, slave relation 7, \(RERO\)vtls004272337
130    False
142    False
dtype: bool

master index 131, slave relation 0, \(IDSBB\)006182500
131    False
264     True
dtype: bool

master index 131, slave relation 1, \(IDSLU\)001075720
131    False
44      True
dtype: bool

master index 132, slave relation 0, \(IDSBB\)003746748
132    False
117     True
dtype: bool

master index 132, slave relation 1, \(IDSSG\)000773287
132    False
297    False
dtype: bool

master index 132, slave relation 2, \(IDSLU\)000451958
132    False
39     False
dtype: bool

master index 132, slave relation 3, \(NEBIS\)005063527
132    False
163    False
dtype: bool

master index 132, slave relation 4, \(RERO\)R004592500
132    False
234    False
dtype: bool

master index 132, slave relation 5, \(SGBN\)000592252
132    False
75     False

dtype: bool

master index 132, slave relation 6, \(BGR\)000336877
132    False
13     False
dtype: bool

master index 133, slave relation 0, \(IDSSG\)000547310
133    False
282    False
dtype: bool

master index 133, slave relation 1, \(RERO\)R007020282
133    False
252    False
dtype: bool

master index 133, slave relation 2, \(RERO\)R007035232
133    False
253    False
dtype: bool

master index 133, slave relation 3, \(VAUD\)991015537709702852
133    False
375    False
dtype: bool

master index 133, slave relation 4, \(VAUD\)991015392639702852
133    False
368    False
dtype: bool

master index 133, slave relation 5, \(RNV\)007035232-41bculausa_network
133    False
375    False
dtype: bool

master index 133, slave relation 6, \(RERO\)007035232
133    False
375    False
dtype: bool

master index 133, slave relation 7, R007035232
133    False
253    False
375     True
dtype: bool

master index 133, slave relation 8, \(EXLNZ-41BCULAUSA_NETWORK\)991007860529702851
133    False
375    False
dtype: bool

master index 133, slave relation 9, \(RNV\)007020282-41bculausa_network
133    False
368    False
dtype: bool

master index 133, slave relation 10, \(RERO\)007020282
133    False
368    False
dtype: bool

master index 133, slave relation 11, R007020282
133    False
252    False
368     True
dtype: bool

master index 133, slave relation 12, \(EXLNZ-41BCULAUSA_NETWORK\)991007674679702851
133    False
368    False
dtype: bool

master index 134, slave relation 0, \(IDSLU\)001031997
134    False
45      True
dtype: bool

master index 134, slave relation 1, \(IDSBB\)005834341
134    False
119     True
dtype: bool

master index 134, slave relation 2, \(NEBIS\)007048067
134    False
177    False
dtype: bool

master index 134, slave relation 3, \(ABN\)000669941
134    False
9      False
dtype: bool

master index 134, slave relation 4, \(SGBN\)001138737
134    False
70     False
dtype: bool

master index 135, slave relation 0, \(NEBIS\)009400395
135    False
184     True
dtype: bool

master index 135, slave relation 1, \(SNL\)vtls000622831
135    False
80     False
dtype: bool

master index 135, slave relation 2, \(Sz\)000622831
135    False
80     False
dtype: bool

master index 136, slave relation 0, \(SNL\)vtls001671238
136    False
93      True
dtype: bool

master index 136, slave relation 1, \(SNL\)vtls001675981
136    False
94     False
dtype: bool

master index 136, slave relation 2, \(Sz\)001671238
136    False
93      True
dtype: bool

master index 136, slave relation 3, \(Sz\)001675981
136    False
94     False
dtype: bool

master index 137, slave relation 0, \(IDSBB\)006708762
137    False
415     True
dtype: bool

master index 137, slave relation 1, \(NEBIS\)010889835
137    False
413     True
dtype: bool

master index 138, slave relation 0, \(SBT\)000060564
138    False
57      True
dtype: bool

master index 138, slave relation 1, \(RERO\)1182227
138    False
196     True
dtype: bool

master index 138, slave relation 2, \(VAUD\)991017147319702852
138    False
362     True
dtype: bool

master index 138, slave relation 3, \(RNV\)001079772-41bculausa_network
138    False
362     True
dtype: bool

master index 138, slave relation 4, \(RERO\)001079772
138    False
362     True
dtype: bool

master index 138, slave relation 5, 1182227
138    False
196     True
362     True
dtype: bool

master index 138, slave relation 6, \(EXLNZ-41BCULAUSA_NETWORK\)991004985239702851
138    False
362     True
dtype: bool

master index 139, slave relation 0, \(IDSBB\)004939759
139    False
108     True
dtype: bool

master index 139, slave relation 1, \(NEBIS\)004173013
139    False
156    False
dtype: bool

master index 140, slave relation 0, \(RERO\)R008517967
140    False
333     True
dtype: bool

master index 140, slave relation 1, \(VAUD\)991021099890002852
140    False
404     True
dtype: bool

master index 140, slave relation 2, R008517967
140    False
333     True
404     True
dtype: bool

master index 140, slave relation 3, \(RERO\)vtls008517967
140    False
404     True
dtype: bool

master index 140, slave relation 4, \(EXLNZ-41BCULAUSA_NETWORK\)991023421026002851
140    False
404     True
dtype: bool

master index 141, slave relation 0, \(RERO\)R274430160
141    False
217     True
dtype: bool

master index 141, slave relation 1, \(VAUD\)991019979819702852
141    False
377     True
dtype: bool

master index 141, slave relation 2, \(RNV\)002744301-41bculausa_network
141    False
377     True
dtype: bool

master index 141, slave relation 3, \(RERO\)002744301
141    False
377     True
dtype: bool

master index 141, slave relation 4, R274430160
141    False
217     True
377     True
dtype: bool

master index 141, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991022784739702851
141    False
377     True
dtype: bool

master index 142, slave relation 0, \(RERO\)R008262893
142    False
294     True
dtype: bool

master index 142, slave relation 1, \(VAUD\)991003829309702852
142    False
374     True
dtype: bool

master index 142, slave relation 2, \(RNV\)008262893-41bculausa_network
142    False
374     True
dtype: bool

master index 142, slave relation 3, \(RERO\)008262893
142    False
374     True
dtype: bool

master index 142, slave relation 4, R008262893
142    False
294     True
374     True
dtype: bool

master index 142, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991018365469702851
142    False
374     True
dtype: bool

master index 143, slave relation 0, \(RERO\)R008395945
143    False
315     True
dtype: bool

master index 143, slave relation 1, \(VAUD\)991005240589702852
143    False
369     True
dtype: bool

master index 143, slave relation 2, \(RNV\)008395945-41bculausa_network
143    False
369     True
dtype: bool

master index 143, slave relation 3, \(RERO\)008395945
143    False
369     True
dtype: bool

master index 143, slave relation 4, R008395945
143    False
315     True
369     True
dtype: bool

master index 143, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991019711029702851
143    False
369     True
dtype: bool

master index 144, slave relation 0, \(RERO\)R008165820
144    False
287     True
dtype: bool

master index 144, slave relation 1, \(VAUD\)991002985029702852
144    False
360     True
dtype: bool

master index 144, slave relation 2, \(RNV\)008165820-41bculausa_network
144    False
360     True
dtype: bool

master index 144, slave relation 3, \(RERO\)008165820
144    False
360     True
dtype: bool

master index 144, slave relation 4, R008165820
144    False
287     True
360     True
dtype: bool

master index 144, slave relation 5, \(EXLNZ-41BCULAUSA_NETWORK\)991017454209702851
144    False
360     True
dtype: bool

master index 145, slave relation 0, \(IDSBB\)003690925
145    False
123     True
dtype: bool

master index 145, slave relation 1, \(NEBIS\)005645758
145    False
169    False
dtype: bool

master index 145, slave relation 2, \(RERO\)R003034172
145    False
222    False
dtype: bool

master index 145, slave relation 3, \(ABN\)000155059
145    False
1      False
dtype: bool

master index 146, slave relation 0, \(IDSSG\)000533501
146    False
52     False
dtype: bool

master index 146, slave relation 1, \(IDSBB\)004404714
146    False
135    False
dtype: bool

master index 146, slave relation 2, \(IDSLU\)000547974
146    False
49     False
dtype: bool

master index 146, slave relation 3, \(NEBIS\)005519625
146    False
189    False
dtype: bool

master index 146, slave relation 4, \(BGR\)000384263
146    False
21     False
dtype: bool

master index 146, slave relation 5, \(ABN\)000327579
146    False
11     False
dtype: bool

master index 146, slave relation 6, \(SGBN\)000887381
146    False
74     False
dtype: bool

master index 147, slave relation 0, \(IDSBB\)004076773
147    False
131    False
dtype: bool

master index 147, slave relation 1, \(ABN\)000295774
147    False
10     False
dtype: bool

master index 147, slave relation 2, \(BGR\)000384903
147    False
15     False
dtype: bool

master index 147, slave relation 3, \(RERO\)R004263905
147    False
232    False
dtype: bool

master index 148, slave relation 0, \(SBT\)000781193
148    False
312    False
dtype: bool

master index 148, slave relation 1, \(RERO\)R008489733
148    False
336    False
dtype: bool

master index 149, slave relation 0, \(RERO\)R003951198
149    False
228     True
dtype: bool

master index 149, slave relation 1, \(HEMU\)27700
149    False
420    False
dtype: bool

master index 150, slave relation 0, \(IDSLU\)000541665
150    False
31      True
dtype: bool

master index 150, slave relation 1, \(HEMU\)1153
150    False
418    False
dtype: bool

master index 151, slave relation 0, \(NEBIS\)005618995
151    False
168    False
dtype: bool

master index 151, slave relation 1, \(HEMU\)35952
151    False
421    False
dtype: bool

master index 152, slave relation 0, \(NEBIS\)006565661
152    False
175     True
dtype: bool

master index 152, slave relation 1, \(SBT\)000243094
152    False
59     False
dtype: bool

master index 153, slave relation 0, \(NEBIS\)006676530
153    False
176    False
dtype: bool

master index 153, slave relation 1, \(SNL\)vtls001635981
153    False
92     False
dtype: bool

master index 153, slave relation 2, \(RERO\)R006080192
153    False
239    False
dtype: bool

master index 153, slave relation 3, \(Sz\)001635981
153    False
92     False
dtype: bool

master index 154, slave relation 0, \(SERSOL\)ssj0000328745
154    False
414    False
dtype: bool

master index 154, slave relation 1, \(SNL\)vtls001719167
154    False
262    False
dtype: bool

master index 154, slave relation 2, \(WaSeSS\)ssj0000328745
154    False
414    False
dtype: bool

master index 154, slave relation 3, \(Sz\)001719167
154    False
262    False
dtype: bool

master index 155, slave relation 0, \(SGBN\)000610425
155    False
76      True
dtype: bool

master index 155, slave relation 1, \(KBTG\)131754
155    False
433    False
dtype: bool

master index 156, slave relation 0, \(IDSBB\)005814130
156    False
115     True
dtype: bool

master index 156, slave relation 1, \(IDSSG\)000416104
156    False
50     False
dtype: bool

master index 156, slave relation 2, \(OCoLC\)65333349
156    False
115     True
dtype: bool

master index 157, slave relation 0, \(IDSBB\)000081376
157    False
132    False
dtype: bool

master index 157, slave relation 1, \(NEBIS\)005269370

157    False
164    False
dtype: bool

master index 157, slave relation 2, \(SBT\)000063881
157    False
60     False
dtype: bool

master index 157, slave relation 3, \(LIBIB\)000059765
157    False
274    False
dtype: bool

master index 157, slave relation 4, \(SNL\)vtls001325614
157    False
87     False
dtype: bool

master index 157, slave relation 5, \(Sz\)001325614
157    False
87     False
dtype: bool

master index 158, slave relation 0, \(NEBIS\)010466244
158    False
290    False
dtype: bool

master index 158, slave relation 1, \(ABN\)000783365
158    False
292    False
dtype: bool

master index 158, slave relation 2, \(ALEX\)9925825300101791
158    False
309    False
dtype: bool

master index 158, slave relation 3, \(SNL\)vtls001795188
158    False
304    False
dtype: bool

master index 158, slave relation 4, \(OCoLC\)881819885
158    False
290    False
292    False
dtype: bool

master index 158, slave relation 5, \(Sz\)001795188
158    False
304    False
dtype: bool

In [15]:
# Look at sample cases
df_m.loc[0], df_s.loc[107]

(035liste      [(IDSBB)002447452, (ALEX)9912923344101791]
 century                                             2000
 coordinate
 corporate
 decade                                              2000
 docid                                          264853032
 doi
 edition
 exactDate                                       2000
 format                                BK020000, BK020800
 isbn                                       0-87834-101-3
 ismn
 musicid
 pages                                             319 S.
 part                                   Vol. 26, 26, 2000
 person                                    100, 700, 245c
 pubinit
 pubword
 pubyear                                         2000
 scale
 ttlfull                                              245
 ttlpart                                              245
 volumes                                           319 S.
 Name: 0, dtype: object, 035liste      (OCoLC)231891290, (IDSBB)002447452
 century                                     2000
 coordinate
 corporate
 decade                                      2000
 docid                                  097764299
 doi
 edition
 exactDate                               2000
 format                                  BK020000
 isbn                               0-87834-101-3
 ismn
 musicid
 pages                                     319 S.
 part                                     Vol. 26
 person                            100, 700, 245c
 pubinit
 pubword
 pubyear                                 2000
 scale
 ttlfull                                      245
 ttlpart                                      245
 volumes                                   319 S.
 Name: 107, dtype: object)

In [16]:
# Look at sample cases, manually
master_index = 2

slave_index = master_slaves_compare(df_m, df_s, master_index, 0)

df_united = pd.concat([df_m.loc[[master_index]], df_s.iloc[slave_index]], axis=0)
df_united

master index 2, slave relation 0, \(IDSLU\)001293605

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
2,"[(IDSLU)001293605, (IDSBB)006725532, (NEBIS)01...",2017,,,2017,264853539,,,2017,BK010000,,,,74 Seiten,Nr. 313 (August 2017),"100, 700, 245c",,,2017,,"245, 246",245,74 Seiten
427,"(OCoLC)1002912504, (IDSLU)001293605",2017,,,2017,494751363,,,2017,BK010000,,,,74 Seiten,Nr. 313 (August 2017),"100, 700, 245c",,,2017,,245,245,74 Seiten

## Find duplicates

In [17]:
def find_duplicates(df):
    df_duplicates = df[df.drop(columns=['035liste', 'docid']).duplicated(keep=False)].sort_values(by='ttlfull')
    
    return df_duplicates

In [18]:
find_duplicates(df_s)

,035liste,century,coordinate,corporate,decade,docid,doi,edition,exactDate,format,isbn,ismn,musicid,pages,part,person,pubinit,pubword,pubyear,scale,ttlfull,ttlpart,volumes
4,"(OCoLC)887324690, (ABN)000548154",2008,,,2008,00351031X,,,2008,BK020000,978-1-4058-8214-9,,,64 S.,,"100, 700, 245c",Pearson Education,Pearson Education,2008,,245,245,64 S.
372,"(VAUD)991004649259702852, (RNV)008339403-41bcu...",2016,,,2016,41487336X,,[Nouv.] éd.,2016,BK020000,978-2-07-046833-1,,,153 p.,"3870., 3870","100, 700, 245c",Gallimard,Gallimard,2016,,245,245,153 p.
371,"(VAUD)991021085980402852, (EXLNZ-41BCULAUSA_NE...",2016,,,2016,41471475X,,,2016,BK020000,978-2-226-31734-6,,,475 p.,,"100, 700, 245c",Albin Michel,Albin Michel,2016,,245,245,475 p.
370,"(VAUD)991002507509702852, (RNV)001419203-41bcu...",1987,,,1987,413117294,,,1987,BK020000,,,,"XIX, 589 p.",4,"100, 245c",Staatlicher Lehrmittelverlag,Staatlicher Lehrmittelverlag,1987,,245,245,"XIX, 589 p."
369,"(VAUD)991005240589702852, (RNV)008395945-41bcu...",2016,,,2016,411396625,,,2016,BK020000,978-0-7294-1157-8,,,332 p.,13 C,"100, 700, 800, 245c",Voltaire Foundation,Voltaire Foundation,2016,,245,245,332 p.
368,"(VAUD)991015392639702852, (RNV)007020282-41bcu...",2012,,,2012,41125572X,,,2012,BK020000,978-3-7255-6535-1,,,244 S.,"63, 63","100, 245c",Schulthess,Schulthess,2012,,245,245,244 S.
366,"(VAUD)991002506909702852, (RNV)001419170-41bcu...",1984,,,1984,410759457,,,1984,BK020000,,,,237 p.,1,"100, 245c",Staatlicher Lehrmittelverlag,Staatlicher Lehrmittelverlag,1984,,245,245,237 p.
365,"(VAUD)991002545759702852, (RNV)001421044-41bcu...",1981,,710,1981,410751979,,,19819999,VM030000,,,,v.,,"100, 700, 245c",Staatlicher Lehrmittelverlag,Staatlicher Lehrmittelverlag,19819999,,245,245,v.
364,"(VAUD)991003937499702852, (RNV)005694081-41bcu...",1997,,710,1997,410690015,,[Nouv. éd.],19972002,BK020000,,,,3 vol.,,"100, 700, 245c",Berner Lehrmittel- und Medienverl.,Berner Lehrmittel- und Medienverl.,19972002,,245,245,3 vol.
363,"(VAUD)991001897789702852, (RNV)000480336-41bcu...",1970,,,1970,40934950X,,,1970,MU010200,,,BA 4553a,1 RÉDUCTION (221 p.),,"100, 700, 245c",Bärenreiter,Bärenreiter,1970,,245,245,1 RÉDUCTION (221 p.)
362,"(VAUD)991017147319702852, (RNV)001079772-41bcu...",1989,,,1989,409345873,,,1989,BK020000,2-08-070552-0,,,192 p.,"552, 552","100, 700, 245c",Flammarion,Flammarion,1989,,245,245,192 p.
360,"(VAUD)991002985029702852, (RNV)008165820-41bcu...",2015,,,2015,405610564,,,2015,BK020000,978-0-7294-0965-0,,,407 p.,13 A,"100, 700, 800, 245c",Voltaire Foundation,Voltaire Foundation,2015,,245,245,407 p.
333,(RERO)R008517967,2016,,,2016,368855635,,,2016,BK020000,978-0-7294-1155-4,,,351 p.,13 D,"100, 700, 800, 245c",Voltaire Foundation,Voltaire Foundation,2016,,245,245,351 p.
332,"(OCoLC)871512737, (ABN)000758696",2009,,,2009,368529266,,,20091990,VM010300,,,502430,1 DVD-Video (ca. 109 Min.),,"100, 700, 245c",Kinowelt Home Entertainment,Kinowelt Home Entertainment,20091990,,245,245,1 DVD-Video (ca. 109 Min.)
331,(RERO)R008488254,2016,,,2016,366803182,,,2016,BK020000,978-2-226-31734-6,,,475 p.,,"100, 700, 245c",Albin Michel,Albin Michel,2016,,245,245,475 p.
428,"(OCoLC)1002177443, (NEBIS)011045420, (OCoLC)10...",2017,,,2017,495381160,10.1055/b-005-143650,"7., überarbeitete und erweiterte Auflage",2017,BK020053,978-3-13-240808-1,10.1055/b-005-143650,,1 Online-Ressource,,"100, 700, 245c",,,2017,,245,245,1 Online-Ressource
313,(RERO)R008339403,2016,,,2016,357341309,,[Nouv.] éd.,2016,BK020000,978-2-07-046833-1,,,153 p.,"3870., 3870","100, 700, 245c",Gallimard,Gallimard,2016,,245,245,153 p.
299,"(OCoLC)180154028, (IDSSG)000785108",2007,,,2007,340715081,,,2007,BK020000,"978-3-7815-1531-4, 3-7815-1531-1",,,304 S.,,"100, 700, 245c",,,2007,,245,245,304 S.
294,(RERO)R008262893,2015,,,2015,339221542,,,2015,BK020000,978-0-7294-1156-1,,,453 p.,13 B,"100, 700, 800, 245c",Voltaire Foundation,Voltaire Foundation,2015,,245,245,453 p.
287,(RERO)R008165820,2015,,,2015,335153038,,,2015,BK020000,978-0-7294-0965-0,,,407 p.,13 A,"100, 700, 800, 245c",Voltaire Foundation,Voltaire Foundation,2015,,245,245,407 p.
283,"(OCoLC)828659420, (IDSLU)001183923",1996,,710,1996,330691031,,,1996,MU040100,,,Erato 0630-12705-2,2 Compact Discs,,"100, 700, 245c",,,1996,,245,245,2 Compact Discs
276,"(OCoLC)731635279, (LIBIB)000315536",2009,,,2009,323173349,,,2009,BK020000,978-3-15-020008-7,,,600 S.,20008,"100, 245c",Reclam,Reclam,2009,,245,245,600 S.
274,"(OCoLC)611250505, (LIBIB)000059765",1970,,,1970,321372808,,,19702006,MU010100,,,BA 4553,1 Partitur,Band 19,"100, 700, 245c",Bärenreiter,Bärenreiter,19702006,,245,245,1 Partitur
264,"(OCoLC)740934536, (IDSBB)006182500",2009,,,2009,303964960,,,20092005,VM010300,,,501326,1 DVD-Video (ca. 82 Min.),,"100, 700, 245c",,,20092005,,245,245,1 DVD-Video (ca. 82 Min.)
373,"(VAUD)991010949619702852, (RNV)003971490-41bcu...",2005,,,2005,414925408,,,2005,BK020000,0-521-82437-0,,,"LXXVII, 600 p.",,"100, 700, 800, 245c",Cambridge Univ. Press,Cambridge Univ. Press,2005,,245,245,"LXXVII, 600 p."
253,(RERO)R007035232,2012,,,2012,251798666,,,2012,BK020300,978-3-7255-6535-1,,,"LX, 244 S.",,"100, 245c",Schulthess,Schulthess,2012,,245,245,"LX, 244 S."
374,"(VAUD)991003829309702852, (RNV)008262893-41bcu...",2015,,,2015,414990331,,,2015,BK020000,978-0-7294-1156-1,,,453 p.,13 B,"100, 700, 800, 245c",Voltaire Foundation,Voltaire Foundation,2015,,245,245,453 p.
376,"(VAUD)991011403159702852, (RNV)004091898-41bcu...",2006,,,2006,415208262,,,2006,BK020000,2-226-17006-5,,,239 p.,,"100, 700, 245c",Albin Michel,Albin Michel,2006,,245,245,239 p.
426,(NEBIS)011007027,1993,,,1993,492162964,,[19.-21.Tsd.],1993,BK020000,,,,281 S.,,"100, 700, 245c",,,1993,,245,245,281 S.
424,"(OCoLC)1002177443, (IDSBB)006726594",2017,,,2017,491629737,10.1055/b-005-143650,"7., überarbeitete und erweiterte Auflage",2017,BK020053,978-3-13-240808-1,10.1055/b-005-143650,,1 Online-Ressource,,"100, 700, 245c",,,2017,,245,245,1 Online-Ressource
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,"(OCoLC)610693897, (IDSBB)000193942",1979,,710,1979,330286005,,,19791999,CR030600,0252-9955,,,,,"100, 245c",,,19791999,,"245, 246",245,
408,"(SNL)vtls001887658, (Sz)001887658",2016,,710,2016,481759859,,,2016,BK020053,,,,1 Online-Ressource,,"100, 245c",,,2016,,"245, 246",245,1 Online-Ressource
409,"(SNL)vtls001887659, (Sz)001887659",2016,,710,2016,481759867,,,2016,BK020053,,,,1 ressource en ligne,,"100, 245c",,,2016,,"245, 246",245,1 ressource en ligne
293,(RERO)R007822798,2015,,710,2015,339178574,,6. Aufl.,20159999,BK020000,978-3-7190-3171-8,,,Bd. 1-,,"100, 700, 245c",Helbing Lichtenhahn,Helbing Lichtenhahn,20159999,,"245, 246",245,Bd. 1-
61,"(OCoLC)635693240, (SBT)000063646",1979,,710,1979,045124809,,,19791999,CR030600,0252-9955,,,v.,,"100, 245c","Klett u. Balmer, Delval, Ed. universitaires","Klett u. Balmer, Delval, Ed. universitaires",19791999,,"245, 246",245,v.
410,"(SNL)vtls001887704, (Sz)001887704",2016,,710,2016,48176030X,,,2016,BK020053,,,,1 ressource en ligne,,"100, 245c",,,2016,,"245, 246",245,1 ressource en ligne
296,"(OCoLC)630213725, (IDSSG)000724644, (OCoLC)630...",1979,,710,1979,34017028X,,,19791999,CR030600,0252-9955,,,,,"100, 245c",,,19791999,,"245, 246",245,
41,"(OCoLC)778329562, (IDSLU)000194125",1979,,710,1979,028813901,,,19791999,CR030600,0252-9955,,,,,"100, 245c",,,19791999,,"245, 246",245,
407,"(SNL)vtls001887640, (Sz)001887640",2016,,710,2016,481759689,,,2016,BK020053,,,,1 Online-Ressource,,"100, 245c",,,2016,,"245, 246",245,1 Online-Ressource
361,"(VAUD)991000042089702852, (RNV)007822798-41bcu...",2015,,710,2015,408600551,,6. Aufl.,20159999,BK020000,978-3-7190-3171-8,,,Bd. 1-,,"100, 700, 245c",Helbing Lichtenhahn,Helbing Lichtenhahn,20159999,,"245, 246",245,Bd. 1-
390,"(SNL)vtls001866901, (Sz)001866901",2014,,710,2014,428866085,,,2014,BK020053,,,,1 Online-Ressource,,"100, 245c",,,2014,,"245, 246",245,1 Online-Ressource
357,"(SNL)vtls001860448, (Sz)001860448",2013,,710,2013,404220762,,,2013,BK020053,,,,1 ressource en ligne,,"100, 245c",,,2013,,"245, 246",245,1 ressource en ligne
367,"(VAUD)991012920519702852, (RNV)000256377-41bcu...",1979,,710,1979,41107220X,,,19791999,CR030600,0252-9955,,,v.,,"100, 245c","Klett u. Balmer, Delval, Ed. universitaires","Klett u. Balmer, Delval, Ed. universitaires",19791999,,"245, 246",245,v.
192,(RERO)0277119,1979,,710,1979,202131610,,,19791999,CR030600,0252-9955,,,v.,,"100, 245c","Klett u. Balmer, Delval, Ed. universitaires","Klett u. Balmer, Delval, Ed. universitaires",19791999,,"245, 246",245,v.
356,"(SNL)vtls001860444, (Sz)001860444",2013,,710,2013,40422072X,,,2013,BK020053,,,,1 ressource en ligne,,"100, 245c",,,2013,,"245, 246",245,1 ressource en ligne
355,"(SNL)vtls001860443, (Sz)001860443",2013,,710,2013,404220711,,,2013,BK020053,,,,1 Online-Ressource,,"100, 245c",,,2013,,"245, 246",245,1 Online-Ressource
354,"(SNL)vtls001860442, (Sz)001860442",2013,,710,2013,404220703,,,2013,BK020053,,,,1 ressource en ligne,,"100, 245c",,,2013,,"245, 246",245,1 ressource en ligne
353,"(SNL)vtls001860441, (Sz)001860441",2013,,710,2013,40422069X,,,2013,BK020053,,,,1 Online-Ressource,,"100, 245c",,,2013,,"245, 246",245,1 Online-Ressource
352,"(SNL)vtls001860440, (Sz)001860440",2013,,710,2013,404220681,,,2013,BK020053,,,,1 Online-Ressource,,"100, 245c",,,2013,,"245, 246",245,1 Online-Ressource
344,"(SNL)vtls001852009, (Sz)001852009",2011,,710,2011,374719632,,,2011,BK020053,,,,,,"100, 245c",Schweizerische Normen-Vereinigung (SNV),Schweizerische Normen-Vereinigung (SNV),2011,,"245, 246",245,
343,"(SNL)vtls001852008, (Sz)001852008",2011,,710,2011,374719624,,,2011,BK020053,,,,,,"100, 245c",Schweizerische Normen-Vereinigung (SNV),Schweizerische Normen-Vereinigung (SNV),2011,,"245, 246",245,
342,"(SNL)vtls001852007, (Sz)001852007",2011,,710,2011,374719616,,,2011,BK020053,,,,,,"100, 245c",Schweizerische Normen-Vereinigung (SNV),Schweizerische Normen-Vereinigung (SNV),2011,,"245, 246",245,
341,"(SNL)vtls001852005, (Sz)001852005",2011,,710,2011,374719594,,,2011,BK020053,,,,,,"100, 245c",Schweizerische Normen-Vereinigung (SNV),Schweizerische Normen-Vereinigung (SNV),2011,,"245, 246",245,
340,"(SNL)vtls001852003, (Sz)001852003",2011,,710,2011,374719578,,,2011,BK020053,,,,,,"100, 245c",Schweizerische Normen-Vereinigung (SNV),Schweizerische Normen-Vereinigung (SNV),2011,,"245, 246",245,
339,"(SNL)vtls001851968, (Sz)001851968",2011,,710,2011,374719225,,,2011,BK020053,,,,,,"100, 245c",Schweizerische Normen-Vereinigung (SNV),Schweizerische Normen-Vereinigung (SNV),2011,,"245, 246",245,
338,"(SNL)vtls001851966, (Sz)001851966",2011,,710,2011,374719209,,,2011,BK020053,,,,,,"100, 245c",Schweizerische Normen-Vereinigung (SNV),Schweizerische Normen-Vereinigung (SNV),2011,,"245, 246",245,
337,"(SNL)vtls001851938, (Sz)001851938",2011,,710,2011,37471892X,,,2011,BK020053,,,,,,"100, 245c",Schweizerische Normen-Vereinigung (SNV),Schweizerische Normen-Vereinigung (SNV),2011,,"245, 246",245,
388,"(SNL)vtls001866899, (Sz)001866899",2014,,710,2014,428866069,,,2014,BK020053,,,,1 Online-Ressource,,"100, 245c",,,2014,,"245, 246",245,1 Online-Ressource
391,"(SNL)vtls001866902, (Sz)001866902",2014,,710,2014,428866093,,,2014,BK020053,,,,1 ressource en ligne,,"100, 245c",,,2014,,"245, 246",245,1 ressource en ligne
389,"(SNL)vtls001866900, (Sz)001866900",2014,,710,2014,428866077,,,2014,BK020053,,,,1 ressource en ligne,,"100, 245c",,,2014,,"245, 246",245,1 ressource en ligne

In [19]:
df_m.loc[90]

035liste      [(RERO)0277119, (VAUD)991012920519702852, (SBT...
century                                                    1979
coordinate
corporate                                                   710
decade                                                     1979
docid                                                 50438984X
doi
edition
exactDate                                              19791999
format                                                 CR030600
isbn                                                  0252-9955
ismn
musicid
pages                                                        v.
part
person                                                100, 245c
pubinit             Klett u. Balmer, Delval, Ed. universitaires
pubword             Klett u. Balmer, Delval, Ed. universitaires
pubyear                                                19791999
scale
ttlfull                                                245, 246
ttlpart                                                     245
volumes                                                      v.
Name: 90, dtype: object

In [20]:
df_s.loc[367], df_s.loc[61]

(035liste      (VAUD)991012920519702852, (RNV)000256377-41bcu...
 century                                                    1979
 coordinate
 corporate                                                   710
 decade                                                     1979
 docid                                                 41107220X
 doi
 edition
 exactDate                                              19791999
 format                                                 CR030600
 isbn                                                  0252-9955
 ismn
 musicid
 pages                                                        v.
 part
 person                                                100, 245c
 pubinit             Klett u. Balmer, Delval, Ed. universitaires
 pubword             Klett u. Balmer, Delval, Ed. universitaires
 pubyear                                                19791999
 scale
 ttlfull                                                245, 246
 ttlpart                                                     245
 volumes                                                      v.
 Name: 367, dtype: object,
 035liste                 (OCoLC)635693240, (SBT)000063646
 century                                              1979
 coordinate
 corporate                                             710
 decade                                               1979
 docid                                           045124809
 doi
 edition
 exactDate                                        19791999
 format                                           CR030600
 isbn                                            0252-9955
 ismn
 musicid
 pages                                                  v.
 part
 person                                          100, 245c
 pubinit       Klett u. Balmer, Delval, Ed. universitaires
 pubword       Klett u. Balmer, Delval, Ed. universitaires
 pubyear                                          19791999
 scale
 ttlfull                                          245, 246
 ttlpart                                               245
 volumes                                                v.
 Name: 61, dtype: object)

In [21]:
print(df_m.decade.unique())

df_m_d_sd = df_m.decade.sort_values()
for i in range(len(df_m_d_sd)):
    print(df_m_d_sd[i])

['2000' '1978' '2017' '2015' '2013' '2007' '1982' '1959' '2016' '1763'
 '1764' '2004' '2002' '1979' '1997' '1960' '1890' '1993' '1900' '1880'
 '1932' '1950' '1970' '1987' '1983' '2003' '1850' '1920' '1977' '1991'
 '1988' '2009' '1996' '1994' '1981' '1976' '1941' '1843' '1956' '18uu'
 '1909' '1984' '1990' '1945' '1989' '1862' '1963' '2001' '2005' '2008'
 '2014' '1700' '2010' '2011' '1998' '1995' '1973' '2006' '1999' '2012'
 '1836' '1876' '1471']
2000
1978
2017
2015
2013
2007
1982
1959
2015
2016
1763
1764
2004
2002
2000
1979
1997
1960
1890
1993
1900
1900
1880
1932
1950
1970
1987
1983
2003
1890
1850
1920
1900
1920
1900
1977
1987
2002
1991
1988
2009
1991
1996
1994
1982
1981
1976
1982
2000
1982
1991
2002
1880
1959
1941
1843
1979
1920
1956
18uu
1987
1993
1909
18uu
2013
1984
1984
1990
1945
1987
1989
1981
1987
1994
2016
1862
1963
2007
2009
1979
2013
2017
2013
2001
2005
2009
2001
2005
2008
1979
1979
2014
2014
2016
1700
2010
2015
2013
2016
2013
2013
1996
2014
2014
2016
2011
2011
2011
2011
1998
1998
1995
2009
2011
2011
2007
1973
2006
1982
1999
2016
2016
2016
1970
2015
2015
2016
2016
1981
2005
2005
2009
2005
2012
2012
1981
2012
2017
1989
2000
2016
2000
2015
2016
2015
2000
2007
2006
2015
2005
2007
1836
1984
2011
1876
2005
1471
1970
2015

In [22]:
print(df_m.exactDate.unique())

df_m_d_sd = df_m.exactDate.sort_values()
for i in range(len(df_m_d_sd)):
    print(df_m_d_sd[i])

['2000    ' '1978    ' '2017    ' '20150201' '201310  ' '2007    '
 '1982    ' '1959    ' '2015    ' '2016    ' '1763    ' '1764    '
 '2004    ' '20022000' '1979    ' '19972002' '1960    ' '18901899'
 '1993    ' '19001996' '19001999' '18801890' '1932    ' '1950    '
 '1970    ' '1987    ' '1983    ' '2003    ' '18901897' '18501875'
 '19201929' '1900    ' '19201930' '19001950' '1977    ' '2002    '
 '19911990' '1988    ' '2009    ' '1991    ' '1996    ' '1994    '
 '1981    ' '1976    ' '19911794' '1880    ' '1941    ' '1843    '
 '1920    ' '19561791' '18uu    ' '1909    ' '2013    ' '19849999'
 '1984    ' '1990    ' '19451966' '1989    ' '19949999' '1862    '
 '1963    ' '19791999' '2001    ' '2005    ' '2008    ' '2014    '
 '17001799' '2010    ' '19969999' '2011    ' '1998    ' '19959999'
 '20091991' '20111201' '19739999' '2006    ' '19829999' '1999    '
 '19702006' '20159999' '19819999' '20092005' '2012    ' '20071990'
 '20062005' '20151475' '1836    ' '18761920' '1471    ']
2000
1978
2017
20150201
201310
2007
1982
1959
2015
2016
1763
1764
2004
20022000
2000
1979
19972002
1960
18901899
1993
19001996
19001999
18801890
1932
1950
1970
1987
1983
2003
18901897
18501875
19201929
1900
19201930
19001950
1977
1987
2002
19911990
1988
2009
1991
1996
1994
1982
1981
1976
1982
2000
1982
19911794
2002
1880
1959
1941
1843
1979
1920
19561791
18uu
1987
1993
1909
18uu
2013
19849999
1984
1990
19451966
1987
1989
1981
1987
19949999
2016
1862
1963
2007
2009
19791999
2013
2017
2013
2001
2005
2009
2001
2005
2008
1979
19791999
2014
2014
2016
17001799
2010
2015
2013
2016
2013
2013
19969999
2014
2014
2016
2011
2011
2011
2011
1998
1998
19959999
20091991
20111201
2011
2007
19739999
2006
19829999
1999
2016
2016
2016
19702006
20159999
2015
2016
2016
19819999
2005
2005
20092005
2005
2012
2012
1981
2012
2017
1989
2000
2016
2000
2015
2016
2015
2000
20071990
20062005
20151475
2005
2007
1836
1984
2011
18761920
2005
1471
19702006
20159999